---
version: "3"

vars:
  TASK_PODMAN_ENABLED: '{{.TASK_PODMAN_ENABLED | default "false"}}'
  TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS: '{{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS | default ".config/podman/requirements.yml"}}'
  TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE: '{{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE | default ".config/podman/playbook.yml"}}'
  TASK_PODMAN_ANSIBLE_INVENTORY_TARGET: "localhost" # DevSkim: ignore DS162092

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  LANGUAGE: "C.UTF-8"
  ANSIBLE_ROLES_PATH: ".config/podman/roles"

tasks:
  install:roles:
    desc: |
      ℹ️ Description:
        Installs required Ansible roles

      🔧 Variables:
        - TASK_PODMAN_ANSIBLE_GALAXY_CMD: Ansible Galaxy command path
        - TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS: Roles requirements file path

      🔐 Preconditions:
        - Dependencies must be installed

      🔄 Execution:
        Installs required Ansible roles
    preconditions:
      - sh: "test -f {{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS}}"
        msg: "❌ Roles requirements file not found at {{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS}}"
    cmds:
      - cmd: echo "🔄 Starting install roles phase"
        silent: true
      - mkdir -p .config/podman/roles
      - "{{.TASK_ANSIBLE_COMMAND}} ansible-galaxy install -r {{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS}} --roles-path .config/podman/roles"
      - cmd: echo "🎉 Install roles phase completed successfully"
        silent: true

  install:
    desc: |
      ℹ️ Description:
        Installs Podman using Ansible automation

      🔧 Variables:
        - TASK_PODMAN_ANSIBLE_CMD: Ansible command path
        - TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE: Ansible playbook location

      🔐 Preconditions:
        - Dependencies must be installed
        - Roles must be installed

      🔄 Execution:
        Runs Ansible playbook for Podman installation
    status:
      - command -v podman &> /dev/null
    preconditions:
      - sh: "test -f {{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE}}"
        msg: "❌ Playbook file not found at {{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE}}"
    cmds:
      - cmd: echo "🔄 Starting podman installation phase"
        silent: true
      - defer: { task: cleanup }
      - task: install:roles
      - |
        {{.TASK_ANSIBLE_COMMAND}} ansible-playbook \
          -i {{.TASK_PODMAN_ANSIBLE_INVENTORY_TARGET}}, \
          -c local \
          {{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE}} \
          -e 'ansible_python_interpreter=/usr/bin/python3'
      - cmd: echo "🎉 Podman installation phase completed successfully"
        silent: true

  cleanup:
    desc: |
      ℹ️ Description:
        Performs cleanup of temporary files and failed installations

      🔧 Variables:
        - TASK_PODMAN_VENV_DIR: Virtual environment to clean

      🔐 Preconditions: None

      🔄 Execution:
        Removes temporary files and partial installations
    internal: true
    cmds:
      - cmd: echo "🔄 Starting cleanup phase"
        silent: true
      - rm -rf .config/podman/roles
      - rm -rf {{.TASK_PODMAN_VENV_DIR}}
      - cmd: echo "🎉 Cleanup phase completed successfully"
        silent: true
