---
version: "3"

vars:
  TASK_PODMAN_ENABLED: '{{.TASK_PODMAN_ENABLED | default "true"}}'
  TASK_PODMAN_VENV_DIR: '{{.TASK_PODMAN_VENV_DIR | default "./venv/podman"}}'
  TASK_PODMAN_ANSIBLE_CMD: '{{.TASK_PODMAN_ANSIBLE_CMD | default "./venv/podman/bin/ansible-playbook"}}'
  TASK_PODMAN_ANSIBLE_GALAXY_CMD: '{{.TASK_PODMAN_ANSIBLE_GALAXY_CMD | default "./venv/podman/bin/ansible-galaxy"}}'
  TASK_PODMAN_ANSIBLE_REQUIREMENTS_FILE: '{{.TASK_PODMAN_ANSIBLE_REQUIREMENTS_FILE | default ".config/podman/requirements.txt"}}'
  TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS: '{{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS | default ".config/podman/requirements.yml"}}'
  TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE: '{{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE | default ".config/podman/playbook.yml"}}'
  TASK_PODMAN_PYTHON_VERSION_FILE: '{{.TASK_PODMAN_PYTHON_VERSION_FILE | default ".config/python/.python-version"}}'
  TASK_PODMAN_ANSIBLE_INVENTORY_TARGET: "localhost" # DevSkim: ignore DS162092

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  LANGUAGE: "C.UTF-8"
  ANSIBLE_ROLES_PATH: ".config/podman/roles"

tasks:
  install:dependencies:
    desc: |
      ℹ️ Description:
        Sets up Ansible and its dependencies in a dedicated virtual environment

      🔧 Variables:
        - TASK_PODMAN_VENV_DIR: Virtual environment location
        - TASK_PODMAN_ANSIBLE_REQUIREMENTS_FILE: Dependencies file path

      🔐 Preconditions:
        - Python 3.x must be installed
        - Internet connectivity required

      🔄 Execution:
        Creates virtualenv and installs required packages
    preconditions:
      - sh: "command -v python3 >/dev/null 2>&1"
        msg: "❌ Python 3 is not installed"
      - sh: "test -f {{.TASK_PODMAN_PYTHON_VERSION_FILE}}"
        msg: "❌ Python version file not found at {{.TASK_PODMAN_PYTHON_VERSION_FILE}}"
      - sh: "test -f {{.TASK_PODMAN_ANSIBLE_REQUIREMENTS_FILE}}"
        msg: "❌ Requirements file not found at {{.TASK_PODMAN_ANSIBLE_REQUIREMENTS_FILE}}"
    cmds:
      - python$(cut -d '=' -f 2 {{.TASK_PODMAN_PYTHON_VERSION_FILE}}) -m venv {{.TASK_PODMAN_VENV_DIR}}
      - "{{.TASK_PODMAN_VENV_DIR}}/bin/pip install -r {{.TASK_PODMAN_ANSIBLE_REQUIREMENTS_FILE}}"
      - cmd: echo "✅ Dependencies installed successfully"
        silent: true

  install:roles:
    desc: |
      ℹ️ Description:
        Installs required Ansible roles

      🔧 Variables:
        - TASK_PODMAN_ANSIBLE_GALAXY_CMD: Ansible Galaxy command path
        - TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS: Roles requirements file path

      🔐 Preconditions:
        - Dependencies must be installed

      🔄 Execution:
        Installs required Ansible roles
    deps: [install:dependencies]
    preconditions:
      - sh: "test -f {{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS}}"
        msg: "❌ Roles requirements file not found at {{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS}}"
    cmds:
      - mkdir -p .config/podman/roles
      - "{{.TASK_PODMAN_ANSIBLE_GALAXY_CMD}} install -r {{.TASK_PODMAN_ANSIBLE_ROLES_REQUIREMENTS}} --roles-path .config/podman/roles"
      - cmd: echo "✅ Ansible roles installed successfully"
        silent: true

  install:
    desc: |
      ℹ️ Description:
        Installs Podman using Ansible automation

      🔧 Variables:
        - TASK_PODMAN_ANSIBLE_CMD: Ansible command path
        - TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE: Ansible playbook location

      🔐 Preconditions:
        - Dependencies must be installed
        - Roles must be installed

      🔄 Execution:
        Runs Ansible playbook for Podman installation
    status:
      - command -v podman &> /dev/null
    preconditions:
      - sh: "test -f {{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE}}"
        msg: "❌ Playbook file not found at {{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE}}"
    cmds:
      - defer: { task: cleanup }
      - task: install:roles
      - |
        {{.TASK_PODMAN_ANSIBLE_CMD}} \
          -i {{.TASK_PODMAN_ANSIBLE_INVENTORY_TARGET}}, \
          -c local \
          {{.TASK_PODMAN_ANSIBLE_PLAYBOOK_FILE}} \
          -e 'ansible_python_interpreter=/usr/bin/python3'
      - cmd: echo "✅ Podman installed successfully"
        silent: true

  cleanup:
    desc: |
      ℹ️ Description:
        Performs cleanup of temporary files and failed installations

      🔧 Variables:
        - TASK_PODMAN_VENV_DIR: Virtual environment to clean

      🔐 Preconditions: None

      🔄 Execution:
        Removes temporary files and partial installations
    internal: true
    cmds:
      - rm -rf .config/podman/roles
      - rm -rf {{.TASK_PODMAN_VENV_DIR}}
      - cmd: echo "✅ Cleanup completed"
        silent: true
