---
image: registry.gitlab.com/digital-commons/devsecops/tools/the-devsecops-plugin:13.1.11

include:
  - local: .config/gitlab/ci/before_script.yml
  - local: .config/gitlab/ci/services.yml
  - local: .config/gitlab/ci/stages.yml
  - local: .config/gitlab/ci/tags.yml
  - local: .config/gitlab/ci/variables.yml
  - local: .config/gitlab/ci/workflow.yml

  - local: .config/gitlab/ci/devsecops/plan.yml
  - local: .config/gitlab/ci/devsecops/code.yml
  - local: .config/gitlab/ci/devsecops/build.yml
  - local: .config/gitlab/ci/devsecops/test.yml
  - local: .config/gitlab/ci/devsecops/release.yml
  - local: .config/gitlab/ci/devsecops/deploy.yml
  - local: .config/gitlab/ci/devsecops/operate.yml
  - local: .config/gitlab/ci/devsecops/monitor.yml
  - local: .config/gitlab/ci/devsecops/feedback.yml
