---
# Taskfile.yml: Central hub for development operations.
version: "3"

dotenv: ['.env', '.env.dist']

vars:
  # Environment variables for task control
  TASK_FLAGS: '{{.TASK_FLAGS | default ""}}'
  TASK_SEPARATOR: '{{.TASK_SEPARATOR | default (print (repeat 120 "-") "\n" (repeat 120 "-") "\n" (repeat 120 "-"))}}'
  TASK_DEVSECOPS_ICON: '{{.TASK_DEVSECOPS_ICON | default "♾️"}}'

# Includes: Specify necessary and additional components for development.
# - Essential includes are required for a successful Docker build.
# - Optional includes extras like tests and lint (not needed for Docker builds)
includes:
  # Essential includes (Required for Docker build and k3s)
  devsecops:plan:
    taskfile: .config/devsecops/Taskfile.plan.yml
  devsecops:code:
    taskfile: .config/devsecops/Taskfile.code.yml
  devsecops:build:
    taskfile: .config/devsecops/Taskfile.build.yml
  devsecops:test:
    taskfile: .config/devsecops/Taskfile.test.yml
  devsecops:release:
    taskfile: .config/devsecops/Taskfile.release.yml
  devsecops:deploy:
    taskfile: .config/devsecops/Taskfile.deploy.yml
  devsecops:operate:
    taskfile: .config/devsecops/Taskfile.operate.yml
  devsecops:monitor:
    taskfile: .config/devsecops/Taskfile.monitor.yml
  devsecops:feedback:
    taskfile: .config/devsecops/Taskfile.feedback.yml
  project:
    taskfile: project/Taskfile.yml

  # Optional includes (For dev, testing, linting, etc.)
  ansible:
    taskfile: .config/ansible/Taskfile.yml
    optional: true
  bun:
    taskfile: .config/bun/Taskfile.yml
    optional: true
  codeceptjs:
    taskfile: .config/codeceptjs/Taskfile.yml
    optional: true
  commitizen:
    taskfile: .config/commitizen/Taskfile.yml
    optional: true
  commitlint:
    taskfile: .config/commitlint/Taskfile.yml
    optional: true
  copier:
    taskfile: .config/copier/Taskfile.yml
    optional: true
  dev:
    taskfile: .config/dev/Taskfile.yml
    optional: true
  docker-ce:
    taskfile: .config/docker-ce/Taskfile.yml
    optional: true
  go:
    taskfile: .config/go/Taskfile.yml
    optional: true
  helm:
    taskfile: .config/helm/Taskfile.yml
    optional: true
  k3d:
    taskfile: .config/k3d/Taskfile.yml
    optional: true
  kaniko:
    taskfile: .config/kaniko/Taskfile.yml
    optional: true
  kind:
    taskfile: .config/kind/Taskfile.yml
    optional: true
  kubectl:
    taskfile: .config/kubectl/Taskfile.yml
    optional: true
  kubeseal:
    taskfile: .config/kubeseal/Taskfile.yaml
    optional: true
  lefthook:
    taskfile: .config/lefthook/Taskfile.yml
    optional: true
  lizard:
    taskfile: .config/lizard/Taskfile.yml
    optional: true
  megalinter:
    taskfile: .config/megalinter/Taskfile.yml
    optional: true
  nodejs:
    taskfile: .config/nodejs/Taskfile.yml
    optional: true
  podman:
    taskfile: .config/podman/Taskfile.yml
    optional: true
  renovate:
    taskfile: .config/renovate/Taskfile.yml
    optional: true
  sealed-secrets:
    taskfile: .config/sealed-secrets/Taskfile.yaml
    optional: true
  yamllint:
    taskfile: .config/yamllint/Taskfile.yml
    optional: true

tasks:
  tdd:
    # Orchestrates Test Driven Development (TDD) workflows.
    aliases:
      - default
    cmds:
      - task: code
      - task: build
      - task: test:tdd

  devsecops:
    # Orchestrates DevSecOps workflows.
    cmds:
      - task: plan
      - task: code
      - task: build
      - task: test
      - task: release
      - task: deploy
      - task: operate
      - task: monitor
      - task: feedback

  plan:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Plan"
        silent: true
      - task: devsecops:plan
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  code:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Code"
        silent: true
      - task: devsecops:code
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  build:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Build"
        silent: true
      - task: devsecops:build
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  test:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Test"
        silent: true
      - task: devsecops:test
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  test:tdd:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Test Tdd"
        silent: true
      - task: devsecops:test:tdd
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  release:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Release"
        silent: true
      - task: devsecops:release
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  deploy:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Deploy"
        silent: true
      - task: devsecops:deploy
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  operate:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Operate"
        silent: true
      - task: devsecops:operate
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  monitor:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Monitor"
        silent: true
      - task: devsecops:monitor
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true

  feedback:
    cmds:
      - cmd: echo "{{.TASK_DEVSECOPS_ICON}} Feedback"
        silent: true
      - task: devsecops:feedback
      - cmd: echo "{{.TASK_SEPARATOR}}"
        silent: true
