---
version: "3"

vars:
  # Control flags
  TASK_CODECEPTJS_ENABLED: '{{.TASK_CODECEPTJS_ENABLED | default "false"}}'
  TASK_CODECEPTJS_CI: '{{.TASK_CODECEPTJS_CI | default "false"}}'

  # Test configuration
  TASK_CODECEPTJS_CONFIG: '{{.TASK_CODECEPTJS_CONFIG | default ".config/codeceptjs/codecept.conf.sample.js"}}'
  TASK_CODECEPTJS_GREP: '{{.TASK_CODECEPTJS_GREP | default ""}}'
  TASK_CODECEPTJS_DEBUG: '{{.TASK_CODECEPTJS_DEBUG | default ""}}'
  TASK_CODECEPTJS_STEPS: '{{.TASK_CODECEPTJS_STEPS | default ""}}'
  TASK_CODECEPTJS_REPORTER: '{{.TASK_CODECEPTJS_REPORTER | default ""}}'
  TASK_CODECEPTJS_VERBOSE: '{{.TASK_CODECEPTJS_VERBOSE | default ""}}'
  TASK_CODECEPTJS_OVERRIDE: '{{.TASK_CODECEPTJS_OVERRIDE | default ""}}'

  # Environment variables
  TASK_CODECEPTJS_ENV_BASE_URL: '{{.TASK_CODECEPTJS_ENV_BASE_URL | default "http://localhost:8080"}}' # DevSkim: ignore DS162092

  # Cache configuration
  TASK_CODECEPTJS_CACHE_DIR: '{{.TASK_CODECEPTJS_CACHE_DIR | default ".cache/codeceptjs/playwright"}}'

tasks:
  playwright:install:
    desc: Install Playwright browsers locally (Chromium, Firefox, WebKit).
    summary: |
      Installs the Playwright browsers required by the CodeceptJS `Playwright` helper.

      - Uses `npx -y` to avoid local dependencies.
      - `playwright install-deps` may require sudo; keep it optional/commented if not available.
      - Browsers are cached in: {{.TASK_CODECEPTJS_CACHE_DIR}}
    env:
      PLAYWRIGHT_BROWSERS_PATH: "{{.TASK_CODECEPTJS_CACHE_DIR}}"
    cmds:
      - cmd: echo "🔧 Installing Playwright browsers (Chromium only) in {{.TASK_CODECEPTJS_CACHE_DIR}}"
        silent: true
      - cmd: mkdir -p "{{.TASK_CODECEPTJS_CACHE_DIR}}"
      - cmd: |
          # Harden npm network in CI to reduce ECONNRESET
          export NPM_CONFIG_FETCH_RETRIES="${NPM_CONFIG_FETCH_RETRIES:-5}"
          export NPM_CONFIG_FETCH_RETRY_FACTOR="${NPM_CONFIG_FETCH_RETRY_FACTOR:-2}"
          export NPM_CONFIG_FETCH_RETRY_MINTIMEOUT="${NPM_CONFIG_FETCH_RETRY_MINTIMEOUT:-20000}"
          export NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT="${NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT:-120000}"
          export NPM_CONFIG_REGISTRY="${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org}"
          npx -y -p playwright playwright install chromium
      - cmd: |
          # install-deps requires root privileges; skip in CI runners
          if [ "{{.TASK_CODECEPTJS_CI}}" == "true" ]; then
            npx -y -p playwright playwright install-deps || true
          else
            echo "ℹ️ Skipping install-deps in CI."
          fi
      - cmd: echo '✅ Playwright setup finished.'
        silent: true

  npx:
    desc: Run CodeceptJS locally via npx (no Docker), with Playwright.
    summary: |
      Run CodeceptJS locally via npx with Playwright.

      Variables: TASK_CODECEPTJS_CONFIG, CODECEPTJS_BASE_URL, CODECEPTJS_BASE_URL_CI, TASK_CODECEPTJS_GREP, TASK_CODECEPTJS_DEBUG
      Example: task codeceptjs:npx CODECEPTJS_BASE_URL=https://localhost:8001 TASK_CODECEPTJS_CONFIG=project/tests/application/codecept.conf.js -- --debug  # DevSkim: ignore DS162092
      Example CI: task codeceptjs:npx CODECEPTJS_BASE_URL=https://localhost:8001 CODECEPTJS_BASE_URL_CI=https://docker:8001 TASK_CODECEPTJS_CONFIG=project/tests/application/codecept.conf.js # DevSkim: ignore DS162092
    deps:
      - task: playwright:install
    vars:
      _FINAL_BASE_URL: '{{if and (eq .TASK_CODECEPTJS_CI "true") .CODECEPTJS_BASE_URL_CI}}{{.CODECEPTJS_BASE_URL_CI}}{{else}}{{.CODECEPTJS_BASE_URL | default .TASK_CODECEPTJS_ENV_BASE_URL}}{{end}}'
    cmds:
      - cmd: echo "🔄 Running CodeceptJS tests via npx (Playwright)"
        silent: true
      - cmd: >-
          CODECEPTJS_BASE_URL={{._FINAL_BASE_URL}}
          PLAYWRIGHT_BROWSERS_PATH={{.TASK_CODECEPTJS_CACHE_DIR}}
          npx -y -p codeceptjs -p playwright -p codeceptjs-resemblehelper
          codeceptjs run --config {{.TASK_CODECEPTJS_CONFIG}}{{if .TASK_CODECEPTJS_GREP}} --grep {{.TASK_CODECEPTJS_GREP}}{{end}}{{if .TASK_CODECEPTJS_DEBUG}} --debug{{end}}{{if .TASK_CODECEPTJS_STEPS}} --steps{{end}}{{if .TASK_CODECEPTJS_REPORTER}} --reporter {{.TASK_CODECEPTJS_REPORTER}}{{end}}{{if .TASK_CODECEPTJS_VERBOSE}} --verbose{{end}}{{if .TASK_CODECEPTJS_OVERRIDE}} --override {{.TASK_CODECEPTJS_OVERRIDE}}{{end}}
          {{.CLI_ARGS}}
      - cmd: echo '🎉 CodeceptJS (npx) tests completed successfully.'
        silent: true
