---
version: "3"

vars:
  # Control flags
  TASK_CODECEPTJS_ENABLED: '{{.TASK_CODECEPTJS_ENABLED | default "false"}}'
  TASK_CODECEPTJS_CI: '{{.TASK_CODECEPTJS_CI | default "false"}}'

  # Test configuration
  TASK_CODECEPTJS_CONFIG: '{{.TASK_CODECEPTJS_CONFIG | default ".config/codeceptjs/codecept.conf.sample.js"}}'
  TASK_CODECEPTJS_GREP: '{{.TASK_CODECEPTJS_GREP | default ""}}'
  TASK_CODECEPTJS_DEBUG: '{{.TASK_CODECEPTJS_DEBUG | default ""}}'
  TASK_CODECEPTJS_STEPS: '{{.TASK_CODECEPTJS_STEPS | default ""}}'
  TASK_CODECEPTJS_REPORTER: '{{.TASK_CODECEPTJS_REPORTER | default ""}}'
  TASK_CODECEPTJS_VERBOSE: '{{.TASK_CODECEPTJS_VERBOSE | default ""}}'
  TASK_CODECEPTJS_OVERRIDE: '{{.TASK_CODECEPTJS_OVERRIDE | default ""}}'

  # Environment variables
  TASK_CODECEPTJS_ENV_BASE_URL: '{{.TASK_CODECEPTJS_ENV_BASE_URL | default "http://localhost:8080"}}' # DevSkim: ignore DS162092

  # Cache configuration
  TASK_CODECEPTJS_CACHE_DIR: '{{.TASK_CODECEPTJS_CACHE_DIR | default ".cache/codeceptjs/playwright"}}'

tasks:
  playwright:install:
    desc: Install Playwright browsers locally (Chromium, Firefox, WebKit).
    summary: |
      Installs the Playwright browsers required by the CodeceptJS `Playwright` helper.

      - Uses `npx -y` to avoid local dependencies.
      - `playwright install-deps` may require sudo; keep it optional/commented if not available.
      - Browsers are cached in: {{.TASK_CODECEPTJS_CACHE_DIR}}
    vars:
      TASK_CODECEPTJS_VERSION_PLAYWRIGHT:
        sh: node -p "require('./.config/codeceptjs/package.json').devDependencies.playwright"
    env:
      PLAYWRIGHT_BROWSERS_PATH: "{{.TASK_CODECEPTJS_CACHE_DIR}}"
    cmds:
      - cmd: echo "ðŸ”§ Installing Playwright browsers (Chromium only) in {{.TASK_CODECEPTJS_CACHE_DIR}}"
        silent: true
      - cmd: mkdir -p "{{.TASK_CODECEPTJS_CACHE_DIR}}"
      - cmd: |
          # Harden npm network in CI to reduce ECONNRESET
          export NPM_CONFIG_FETCH_RETRIES="${NPM_CONFIG_FETCH_RETRIES:-5}"
          export NPM_CONFIG_FETCH_RETRY_FACTOR="${NPM_CONFIG_FETCH_RETRY_FACTOR:-2}"
          export NPM_CONFIG_FETCH_RETRY_MINTIMEOUT="${NPM_CONFIG_FETCH_RETRY_MINTIMEOUT:-20000}"
          export NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT="${NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT:-120000}"
          export NPM_CONFIG_REGISTRY="${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org}"
          npx -y -p playwright@{{.TASK_CODECEPTJS_VERSION_PLAYWRIGHT}} playwright install chromium
      - cmd: |
          # install-deps requires root privileges; skip in CI runners
          if [ "{{.TASK_CODECEPTJS_CI}}" == "true" ]; then
            npx -y -p playwright@{{.TASK_CODECEPTJS_VERSION_PLAYWRIGHT}} playwright install-deps || true
          else
            echo "â„¹ï¸ Skipping install-deps in CI."
          fi
      - cmd: echo 'âœ… Playwright setup finished.'
        silent: true

  npx:
    desc: Run CodeceptJS locally via npx (no Docker), with Playwright.
    summary: |
      Run CodeceptJS locally via npx with Playwright.

      Variables: TASK_CODECEPTJS_CONFIG, CODECEPTJS_BASE_URL, CODECEPTJS_BASE_URL_CI, TASK_CODECEPTJS_GREP, TASK_CODECEPTJS_DEBUG
      Example: task codeceptjs:npx CODECEPTJS_BASE_URL=https://localhost:8001 TASK_CODECEPTJS_CONFIG=project/tests/application/codecept.conf.js -- --debug  # DevSkim: ignore DS162092
      Example CI: task codeceptjs:npx CODECEPTJS_BASE_URL=https://localhost:8001 CODECEPTJS_BASE_URL_CI=https://docker:8001 TASK_CODECEPTJS_CONFIG=project/tests/application/codecept.conf.js # DevSkim: ignore DS162092
    deps:
      - task: playwright:install
    vars:
      # Versions from package.json (evaluated at task runtime, after Node.js is available)
      TASK_CODECEPTJS_VERSION_CODECEPTJS:
        sh: node -p "require('./.config/codeceptjs/package.json').devDependencies.codeceptjs"
      TASK_CODECEPTJS_VERSION_PLAYWRIGHT:
        sh: node -p "require('./.config/codeceptjs/package.json').devDependencies.playwright"
      TASK_CODECEPTJS_VERSION_VISUAL_HELPER:
        sh: node -p "require('./.config/codeceptjs/package.json').devDependencies['@digital-commons-official/codeceptjs-visual-helper']"
      # Packages to install via npx
      TASK_CODECEPTJS_PACKAGE_CODECEPTJS: '{{.TASK_CODECEPTJS_PACKAGE_CODECEPTJS | default (printf "-p codeceptjs@%s" .TASK_CODECEPTJS_VERSION_CODECEPTJS)}}'
      TASK_CODECEPTJS_PACKAGE_PLAYWRIGHT: '{{.TASK_CODECEPTJS_PACKAGE_PLAYWRIGHT | default (printf "-p playwright@%s" .TASK_CODECEPTJS_VERSION_PLAYWRIGHT)}}'
      TASK_CODECEPTJS_PACKAGE_VISUAL_HELPER: '{{.TASK_CODECEPTJS_PACKAGE_VISUAL_HELPER | default (printf "-p @digital-commons-official/codeceptjs-visual-helper@%s" .TASK_CODECEPTJS_VERSION_VISUAL_HELPER)}}'
      TASK_CODECEPTJS_PACKAGE_EXTRA: '{{.TASK_CODECEPTJS_PACKAGE_EXTRA | default ""}}'
      _FINAL_BASE_URL: '{{if and (eq .TASK_CODECEPTJS_CI "true") .CODECEPTJS_BASE_URL_CI}}{{.CODECEPTJS_BASE_URL_CI}}{{else}}{{.CODECEPTJS_BASE_URL | default .TASK_CODECEPTJS_ENV_BASE_URL}}{{end}}'
    cmds:
      - cmd: echo "ðŸ”„ Running CodeceptJS tests via npx (Playwright)"
        silent: true
      - cmd: >-
          CODECEPTJS_BASE_URL={{._FINAL_BASE_URL}}
          PLAYWRIGHT_BROWSERS_PATH={{.TASK_CODECEPTJS_CACHE_DIR}}
          npx -y {{.TASK_CODECEPTJS_PACKAGE_CODECEPTJS}} {{.TASK_CODECEPTJS_PACKAGE_PLAYWRIGHT}} {{.TASK_CODECEPTJS_PACKAGE_VISUAL_HELPER}} {{.TASK_CODECEPTJS_PACKAGE_EXTRA}}
          codeceptjs run --config {{.TASK_CODECEPTJS_CONFIG}}{{if .TASK_CODECEPTJS_GREP}} --grep {{.TASK_CODECEPTJS_GREP}}{{end}}{{if .TASK_CODECEPTJS_DEBUG}} --debug{{end}}{{if .TASK_CODECEPTJS_STEPS}} --steps{{end}}{{if .TASK_CODECEPTJS_REPORTER}} --reporter {{.TASK_CODECEPTJS_REPORTER}}{{end}}{{if .TASK_CODECEPTJS_VERBOSE}} --verbose{{end}}{{if .TASK_CODECEPTJS_OVERRIDE}} --override {{.TASK_CODECEPTJS_OVERRIDE}}{{end}}
          {{.CLI_ARGS}}
      - cmd: echo 'ðŸŽ‰ CodeceptJS (npx) tests completed successfully.'
        silent: true

  docker:
    desc: Run CodeceptJS via Docker with Playwright.
    summary: |
      Run CodeceptJS inside a Docker container using the official Playwright image.
      This ensures identical rendering on macOS, Linux, and CI.

      Variables: TASK_CODECEPTJS_CONFIG, CODECEPTJS_TESTS_PATH
    vars:
      _CODECEPTJS_CONFIG: '{{.TASK_CODECEPTJS_CONFIG | default ".config/codeceptjs/codecept.conf.sample.js"}}'
      _CODECEPTJS_TESTS_PATH_HOST: '{{.TASK_CODECEPTJS_TESTS_PATH_HOST | default "."}}'
      _CODECEPTJS_TESTS_PATH_CONTAINER: '{{.TASK_CODECEPTJS_TESTS_PATH_CONTAINER | default "/app"}}'
      _CODECEPTJS_SERVICE_NAME: '{{.TASK_CODECEPTJS_SERVICE_NAME | default "codeceptjs"}}'
      _CODECEPTJS_COMPOSE_COMMAND: '{{.TASK_CODECEPTJS_COMPOSE_COMMAND | default "docker compose -f .config/codeceptjs/docker-compose.sample.yml"}}'
    cmds:
      # 1. Start the container and wait for healthcheck
      - cmd: |
          {{._CODECEPTJS_COMPOSE_COMMAND}} up -d {{._CODECEPTJS_SERVICE_NAME}} --wait
      # 2. Cleanup: Wipe the target directory inside the container first.
      # This prevents "zombie files" (files deleted on host but remaining in container) from corrupting the run.
      - cmd: |
          {{._CODECEPTJS_COMPOSE_COMMAND}} exec -T {{._CODECEPTJS_SERVICE_NAME}} rm -rf {{._CODECEPTJS_TESTS_PATH_CONTAINER}}
        ignore_error: true
      # 3. Create the directory structure inside container
      - cmd: |
          {{._CODECEPTJS_COMPOSE_COMMAND}} exec -T {{._CODECEPTJS_SERVICE_NAME}} mkdir -p {{._CODECEPTJS_TESTS_PATH_CONTAINER}}
      # 4. Sync Code: Host -> Container
      - cmd: |
          {{._CODECEPTJS_COMPOSE_COMMAND}} cp {{._CODECEPTJS_TESTS_PATH_HOST}}/. {{._CODECEPTJS_SERVICE_NAME}}:{{._CODECEPTJS_TESTS_PATH_CONTAINER}}/
      # 5. Schedule Sync Back with defer: Container -> Host (Artifacts retrieval)
      # This runs at the end, regardless of test success/failure.
      - defer: |
          echo "ðŸ“¥ Syncing artifacts (reports/screenshots) back to host..."
          {{._CODECEPTJS_COMPOSE_COMMAND}} cp {{._CODECEPTJS_SERVICE_NAME}}:{{._CODECEPTJS_TESTS_PATH_CONTAINER}}/. {{._CODECEPTJS_TESTS_PATH_HOST}}/
        ignore_error: true
      # 6. Run Tests
      # Note: Added '-T' to disable TTY allocation, ensuring stability in CI environments (Jenkins/GitLab).
      - cmd: |
          {{._CODECEPTJS_COMPOSE_COMMAND}} exec -T {{._CODECEPTJS_SERVICE_NAME}} /usr/local/bin/codeceptjs run --config {{._CODECEPTJS_CONFIG}} {{.CLI_ARGS}}
      - cmd: echo 'ðŸŽ‰ CodeceptJS (Docker) tests completed successfully.'
        silent: true
