---
- name: Install Kubeseal using Go
  hosts: localhost # DevSkim: ignore DS162092 # Debug context restricted to development environments
  connection: local
  gather_facts: true

  vars:
    kubeseal_version: "{{ kubeseal_version | default('v0.28.0') }}"
    go_bin_path: "{{ ansible_env.HOME }}/go/bin"

  tasks:
    - name: Check if Go is installed
      ansible.builtin.command: "/usr/local/go/bin/go version"
      register: go_check
      changed_when: false
      # rc=127 is expected if the command is not found (Go not installed)
      failed_when: go_check.rc != 0 and go_check.rc != 127

    - name: Fail if Go is not installed
      ansible.builtin.fail:
        msg: "Go is required but not installed. Please install Go before running this playbook."
      when: go_check.rc != 0

    - name: Ensure GOPATH/bin directory exists
      ansible.builtin.file:
        path: "{{ go_bin_path }}"
        state: directory
        mode: '0755'

    - name: Install Kubeseal using Go install
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin_path }}"
        GOPATH: "{{ ansible_env.HOME }}/go"
      ansible.builtin.shell: |
        /usr/local/go/bin/go install github.com/bitnami-labs/sealed-secrets/cmd/kubeseal@{{ kubeseal_version }}
      args:
        creates: "{{ go_bin_path }}/kubeseal"
        executable: /bin/bash

    - name: Create symlink to kubeseal in /usr/local/bin for global access
      ansible.builtin.file:
        src: "{{ go_bin_path }}/kubeseal"
        dest: "/usr/local/bin/kubeseal"
        state: link
        mode: '0755'
      become: true
      register: symlink_result
      failed_when: symlink_result.failed and not ansible_check_mode

    - name: Alternative - Copy kubeseal to /usr/local/bin if symlink fails (permissions issue)
      ansible.builtin.copy:
        src: "{{ go_bin_path }}/kubeseal"
        dest: "/usr/local/bin/kubeseal"
        mode: '0755'
        remote_src: true
      become: true
      register: copy_result
      failed_when: copy_result.failed and not ansible_check_mode
      when: symlink_result.failed and not ansible_check_mode

    - name: Verify Kubeseal installation in GOPATH
      ansible.builtin.command: "{{ go_bin_path }}/kubeseal --version"
      register: kubeseal_version_check
      changed_when: false

    - name: Verify Kubeseal is accessible globally
      ansible.builtin.command: "which kubeseal"
      register: kubeseal_which_check
      changed_when: false
      # rc=1 is expected if the command cannot find Kubeseal
      failed_when: kubeseal_which_check.rc > 1

    - name: Display Kubeseal path
      ansible.builtin.debug:
        msg: "Kubeseal is available at: {{ kubeseal_which_check.stdout }}"
      when: kubeseal_which_check.rc == 0

    - name: Display installation result
      ansible.builtin.debug:
        msg: "Kubeseal {{ kubeseal_version }} has been successfully installed and made available globally through /usr/local/bin/kubeseal"
      when: kubeseal_version_check.rc == 0
