---
version: "3"

# Note: This is a test to ensure that the tool functions correctly and is mastered before being fully integrated into the project.

vars:
  TASK_DEPENDENCY_CHECK_USER: '{{.TASK_DEPENDENCY_CHECK_USER | default ""}}'
  TASK_DEPENDENCY_CHECK_VERSION: "latest"
  TASK_DEPENDENCY_CHECK_DIRECTORY: "{{.HOME}}/OWASP-Dependency-Check"
  TASK_DEPENDENCY_CHECK_PROJECT: "dependency-check scan: {{.PWD}}"
  TASK_DEPENDENCY_CHECK_DATA_DIRECTORY: "{{.TASK_DEPENDENCY_CHECK_DIRECTORY}}/data"
  TASK_DEPENDENCY_CHECK_CACHE_DIRECTORY: "{{.TASK_DEPENDENCY_CHECK_DIRECTORY}}/data/cache"
  TASK_DEPENDENCY_CHECK_REPORT_DIRECTORY: "{{.PWD}}/odc-reports"

tasks:
  setup:
    desc: Prepare directories for Dependency-Check.
    cmds:
      - cmd: echo "🔄 Preparing directories for Dependency-Check"
        silent: true
      - mkdir -p {{.TASK_DEPENDENCY_CHECK_DATA_DIRECTORY}}
      - mkdir -p {{.TASK_DEPENDENCY_CHECK_CACHE_DIRECTORY}}
      - mkdir -p {{.TASK_DEPENDENCY_CHECK_REPORT_DIRECTORY}}
      - cmd: echo '🎉 Directories prepared for Dependency-Check.'
        silent: true

  pull:
    desc: Download latest Dependency-Check Docker image.
    cmds:
      - cmd: echo "🔄 Downloading latest Dependency-Check Docker image"
        silent: true
      - docker pull owasp/dependency-check:{{.TASK_DEPENDENCY_CHECK_VERSION}}
      - cmd: echo '🎉 Dependency-Check Docker image downloaded.'
        silent: true

  analyze:
    desc: Run Dependency-Check analysis.
    deps: [setup, pull]
    cmds:
      - cmd: echo "🔄 Running Dependency-Check analysis"
        silent: true
      - |
        docker run --rm \
          -e user={{.TASK_DEPENDENCY_CHECK_USER}} \
          --volume {{.PWD}}:/project:z \
          --volume {{.TASK_DEPENDENCY_CHECK_DATA_DIRECTORY}}:/usr/share/dependency-check/data:z \
          --volume {{.TASK_DEPENDENCY_CHECK_REPORT_DIRECTORY}}:/report:z \
          owasp/dependency-check:{{.TASK_DEPENDENCY_CHECK_VERSION}} \
          --scan /project \
          --format "ALL" \
          --project "{{.TASK_DEPENDENCY_CHECK_PROJECT}}" \
          --out /report
      - cmd: echo '🎉 Dependency-Check analysis completed. Reports available in {{.TASK_DEPENDENCY_CHECK_REPORT_DIRECTORY}}'
        silent: true

  clean:
    desc: Remove Dependency-Check data and reports.
    cmds:
      - cmd: echo "🔄 Cleaning up Dependency-Check data and reports"
        silent: true
      - rm -rf {{.TASK_DEPENDENCY_CHECK_DIRECTORY}}
      - rm -rf {{.TASK_DEPENDENCY_CHECK_REPORT_DIRECTORY}}
      - cmd: echo '🎉 Dependency-Check data and reports removed.'
        silent: true

  # Note: There's no direct update command in the Docker example,
  # but pulling the latest image serves a similar purpose
  update:
    desc: Update Dependency-Check Docker image.
    cmds:
      - cmd: echo "🔄 Updating Dependency-Check Docker image"
        silent: true
      - task: pull
      - cmd: echo '🎉 Dependency-Check Docker image updated.'
        silent: true
