---
version: "3"

vars:
  TASK_KIND_ENABLED: '{{.TASK_KIND_ENABLED | default "false"}}'
  TASK_KIND_ANSIBLE_PLAYBOOK_FILE: '{{.TASK_KIND_ANSIBLE_PLAYBOOK_FILE | default ".config/kind/playbook.yml"}}'
  TASK_KIND_ANSIBLE_INVENTORY_TARGET: "localhost" # DevSkim: ignore DS162092
  TASK_KIND_VERSION: '{{.TASK_KIND_VERSION | default "v0.26.0"}}'

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  LANGUAGE: "C.UTF-8"

tasks:
  install:
    desc: |
      ℹ️ Description:
        Installs Kind using Ansible automation

      🔧 Variables:
        - TASK_KIND_ANSIBLE_CMD: Ansible command path
        - TASK_KIND_ANSIBLE_PLAYBOOK_FILE: Ansible playbook location
        - TASK_KIND_VERSION: Version of Kind to install (default: v0.20.0)

      🔐 Preconditions:
        - Dependencies must be installed

      🔄 Execution:
        Runs Ansible playbook for Kind installation
    status:
      - command -v kind &> /dev/null
    preconditions:
      - sh: "test -f {{.TASK_KIND_ANSIBLE_PLAYBOOK_FILE}}"
        msg: "❌ Playbook file not found at {{.TASK_KIND_ANSIBLE_PLAYBOOK_FILE}}"
    cmds:
      - cmd: echo "🔄 Starting kind installation phase"
        silent: true
      - |
        {{.TASK_ANSIBLE_COMMAND}} ansible-playbook \
          -i {{.TASK_KIND_ANSIBLE_INVENTORY_TARGET}}, \
          -e "kind_version={{.TASK_KIND_VERSION}}" \
          {{.TASK_KIND_ANSIBLE_PLAYBOOK_FILE}}
      - task: cleanup
      - cmd: echo "🎉 Kind installation phase completed successfully"
        silent: true

  cleanup:
    desc: Removes temporary files and directories
    cmds:
      - cmd: echo "🔄 Starting cleanup phase"
        silent: true
      - cmd: rm -rf {{.TASK_KIND_VENV_DIR}}
        ignore_error: true
      - cmd: echo "🎉 Cleanup phase completed successfully"
        silent: true
