---
APPLY_FIXES:
  - JSON_PRETTIER
  - YAML_PRETTIER

DISABLE_LINTERS:
  - JSON_V8R
  - YAML_V8R
  - COPYPASTE_JSCPD
  - ANSIBLE_ANSIBLE_LINT

EXCLUDED_DIRECTORIES:
  - .ansible
  - .cache
  - .config/podman/roles
  - .git
  - megalinter-reports
  - vendor
  - venv

ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .config/ansible-lint/config.yaml
COPYPASTE_JSCPD_CONFIG_FILE: .config/jscpd/config.json
GHERKIN_GHERKIN_LINT_CONFIG_FILE: .config/gherkin-lint/config.json
REPOSITORY_DEVSKIM_CONFIG_FILE: .config/devskim/config.json
REPOSITORY_GITLEAKS_CONFIG_FILE: .config/gitleaks/config.toml
REPOSITORY_GRYPE_CONFIG_FILE: .config/grype/config.yml
REPOSITORY_KICS_CONFIG_FILE: .config/kics/config.yml
REPOSITORY_TRIVY_CONFIG_FILE: .config/trivy/config.yml
SPELL_CSPELL_CONFIG_FILE: .config/cspell/config.json
SPELL_LYCHEE_CONFIG_FILE: .config/lychee/config.toml
SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: '(package-lock\.json)'
YAML_YAMLLINT_CONFIG_FILE: .config/yamllint/config.yml
REPOSITORY_DUSTILOCK_ARGUMENTS: "--path project"

SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true
CLEAR_REPORT_FOLDER: true
PARALLEL_PROCESS_NUMBER: 2 # Limiting to 2 cores is necessary to prevent Dustilock or Checkov from crashing.

PRE_COMMANDS:
  # - command: cd /tmp/lint && mkdir -p /usr/share/ansible && find . -type f \( -iname 'requirements.yml' -o -iname 'requirements.yaml' \) -print0 | xargs -0 -I{} sh -c 'grep -Eq "^[[:space:]]*collections[[:space:]]*:" "{}" && ansible-galaxy collection install -r "{}" -p /usr/share/ansible/collections || ansible-galaxy role install -r "{}" --roles-path /usr/share/ansible/roles'
  - command: |
      npm install -g \
        @cspell/dict-companies \
        @cspell/dict-en-gb \
        @cspell/dict-fr-fr \
        @cspell/dict-python \
        @cspell/dict-software-terms

POST_COMMANDS:
  - command: test ! -d /tmp/lint/.ansible || chmod -R 777 /tmp/lint/.ansible
  - command: test ! -d /tmp/lint/.cache || chmod -R 777 /tmp/lint/.cache
  - command: test ! -d /tmp/lint/megalinter-reports || chmod -R 777 /tmp/lint/megalinter-reports
  - command: test ! -d /tmp/lint/.ansible || chown -R 1000:1000 /tmp/lint/.ansible
  - command: test ! -d /tmp/lint/.cache || chown -R 1000:1000 /tmp/lint/.cache
  - command: test ! -d /tmp/lint/megalinter-reports || chown -R 1000:1000 /tmp/lint/megalinter-reports

# Ignore only import errors E0401
PYTHON_PYLINT_ARGUMENTS:
  - --disable=E0401
# Create a pyrightconfig.json file to ignore import errors
PYTHON_PYRIGHT_PRE_COMMANDS:
  - command: |
      echo '{
        "reportMissingImports": false,
        "reportMissingModuleSource": false
      }' > pyrightconfig.json
    continue_if_failed: false
