---
version: "3"

vars:
  TASK_MEGALINTER_CONTAINER_NAME: '{{.OVERRIDE_TASK_MEGALINTER_CONTAINER_NAME | default "megalinter-container"}}'
  TASK_MEGALINTER_CONTZINR_VERSION: '{{.OVERRIDE_TASK_MEGALINTER_CONTZINR_VERSION | default "v7"}}'

tasks:
  default:
    desc: Run MegaLinter for comprehensive code analysis.
    preconditions:
      - sh: "command -v docker &> /dev/null"
        msg: "❌ Docker is not installed. Please run the 'docker:install' task first."
    cmds:
      - docker rm -f {{.TASK_MEGALINTER_CONTAINER_NAME}}
      - sudo rm -rf ./megalinter-reports
      - defer: docker rm -f {{.TASK_MEGALINTER_CONTAINER_NAME}}
      - defer: docker cp {{.TASK_MEGALINTER_CONTAINER_NAME}}:/tmp/lint/megalinter-reports ./megalinter-reports && sudo chown -R $(id -u):$(id -g) megalinter-reports
      - docker run --rm -d --name {{.TASK_MEGALINTER_CONTAINER_NAME}} -e MEGALINTER_CONFIG='.config/megalinter/config.yml' -v /var/run/docker.sock:/var/run/docker.sock:rw --entrypoint sleep oxsecurity/megalinter:{{.TASK_MEGALINTER_CONTZINR_VERSION}} infinity
      - docker cp {{.USER_WORKING_DIR}} {{.TASK_MEGALINTER_CONTAINER_NAME}}:/tmp/lint
      - docker exec {{.TASK_MEGALINTER_CONTAINER_NAME}} /bin/bash /entrypoint.sh
      - cmd: echo "🎉 All files correctly linted with megalinter!"
        silent: true
