---
version: "3"

vars:
  TASK_NODEJS_ENABLED: '{{.TASK_NODEJS_ENABLED | default "true"}}'
  TASK_NODEJS_VENV_DIR: '{{.TASK_NODEJS_VENV_DIR | default "./venv/nodejs"}}'
  TASK_NODEJS_ANSIBLE_CMD: '{{.TASK_NODEJS_ANSIBLE_CMD | default "./venv/nodejs/bin/ansible-playbook"}}'
  TASK_NODEJS_ANSIBLE_GALAXY_CMD: '{{.TASK_NODEJS_ANSIBLE_GALAXY_CMD | default "./venv/nodejs/bin/ansible-galaxy"}}'
  TASK_NODEJS_ANSIBLE_REQUIREMENTS_FILE: '{{.TASK_NODEJS_ANSIBLE_REQUIREMENTS_FILE | default ".config/nodejs/requirements.txt"}}'
  TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS: '{{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS | default ".config/nodejs/requirements.yml"}}'
  TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE: '{{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE | default ".config/nodejs/playbook.yml"}}'
  TASK_NODEJS_PYTHON_VERSION_FILE: '{{.TASK_NODEJS_PYTHON_VERSION_FILE | default ".config/python/.python-version"}}'
  TASK_NODEJS_ANSIBLE_INVENTORY_TARGET: "localhost" # DevSkim: ignore DS162092
  TASK_NODEJS_MAJOR_VERSION: '{{.TASK_NODEJS_MAJOR_VERSION | default "20.x"}}'

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  LANGUAGE: "C.UTF-8"
  ANSIBLE_ROLES_PATH: ".config/nodejs/roles"

tasks:
  install:dependencies:
    desc: |
      ℹ️ Description:
        Sets up Ansible and its dependencies in a dedicated virtual environment

      🔧 Variables:
        - TASK_NODEJS_VENV_DIR: Virtual environment location
        - TASK_NODEJS_ANSIBLE_REQUIREMENTS_FILE: Dependencies file path

      🔐 Preconditions:
        - Python 3.x must be installed
        - Internet connectivity required

      🔄 Execution:
        Creates virtualenv and installs required packages
    preconditions:
      - sh: "command -v python3 >/dev/null 2>&1"
        msg: "❌ Python 3 is not installed"
      - sh: "test -f {{.TASK_NODEJS_PYTHON_VERSION_FILE}}"
        msg: "❌ Python version file not found at {{.TASK_NODEJS_PYTHON_VERSION_FILE}}"
      - sh: "test -f {{.TASK_NODEJS_ANSIBLE_REQUIREMENTS_FILE}}"
        msg: "❌ Requirements file not found at {{.TASK_NODEJS_ANSIBLE_REQUIREMENTS_FILE}}"
    cmds:
      - python$(cut -d '=' -f 2 {{.TASK_NODEJS_PYTHON_VERSION_FILE}}) -m venv {{.TASK_NODEJS_VENV_DIR}}
      - "{{.TASK_NODEJS_VENV_DIR}}/bin/pip install -r {{.TASK_NODEJS_ANSIBLE_REQUIREMENTS_FILE}}"
      - cmd: echo "✅ Dependencies installed successfully"
        silent: true

  install:roles:
    desc: |
      ℹ️ Description:
        Installs required Ansible roles

      🔧 Variables:
        - TASK_NODEJS_ANSIBLE_GALAXY_CMD: Ansible Galaxy command path
        - TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS: Roles requirements file path

      🔐 Preconditions:
        - Dependencies must be installed

      🔄 Execution:
        Installs required Ansible roles
    deps: [install:dependencies]
    preconditions:
      - sh: "test -f {{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS}}"
        msg: "❌ Roles requirements file not found at {{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS}}"
    cmds:
      - mkdir -p .config/nodejs/roles
      - "{{.TASK_NODEJS_ANSIBLE_GALAXY_CMD}} install -r {{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS}} --roles-path .config/nodejs/roles"
      - cmd: echo "✅ Ansible roles installed successfully"
        silent: true

  install:
    desc: |
      ℹ️ Description:
        Installs Node.js using Ansible automation

      🔧 Variables:
        - TASK_NODEJS_ANSIBLE_CMD: Ansible command path
        - TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE: Ansible playbook location
        - TASK_NODEJS_MAJOR_VERSION: Major version of Node.js to install (default: 20.x)

      🔐 Preconditions:
        - Dependencies must be installed
        - Roles must be installed

      🔄 Execution:
        Runs Ansible playbook for Node.js installation
    status:
      - command -v node &> /dev/null
    preconditions:
      - sh: "test -f {{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE}}"
        msg: "❌ Playbook file not found at {{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE}}"
    cmds:
      - defer: { task: cleanup }
      - task: install:roles
      - |
        {{.TASK_NODEJS_ANSIBLE_CMD}} \
          -i {{.TASK_NODEJS_ANSIBLE_INVENTORY_TARGET}}, \
          -c local \
          -e "nodejs_version={{.TASK_NODEJS_MAJOR_VERSION}}" \
          {{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE}}
      - cmd: echo "✅ Node.js installed successfully"
        silent: true

  cleanup:
    internal: true
    cmds:
      - rm -rf .config/nodejs/roles
      - rm -rf {{.TASK_NODEJS_VENV_DIR}}
      - cmd: echo "✅ Cleanup completed"
        silent: true
