---
version: "3"

vars:
  TASK_NODEJS_ENABLED: '{{.TASK_NODEJS_ENABLED | default "true"}}'
  TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS: '{{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS | default ".config/nodejs/requirements.yml"}}'
  TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE: '{{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE | default ".config/nodejs/playbook.yml"}}'
  TASK_NODEJS_ANSIBLE_INVENTORY_TARGET: "localhost" # DevSkim: ignore DS162092
  TASK_NODEJS_MAJOR_VERSION: '{{.TASK_NODEJS_MAJOR_VERSION | default "20.x"}}'

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  LANGUAGE: "C.UTF-8"
  ANSIBLE_ROLES_PATH: ".config/nodejs/roles"

tasks:
  install:roles:
    desc: |
      ℹ️ Description:
        Installs required Ansible roles

      🔧 Variables:
        - TASK_NODEJS_ANSIBLE_GALAXY_CMD: Ansible Galaxy command path
        - TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS: Roles requirements file path

      🔐 Preconditions:
        - Dependencies must be installed

      🔄 Execution:
        Installs required Ansible roles
    preconditions:
      - sh: "test -f {{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS}}"
        msg: "❌ Roles requirements file not found at {{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS}}"
    cmds:
      - cmd: echo "🔄 Starting install roles phase"
        silent: true
      - mkdir -p .config/nodejs/roles
      - "{{.TASK_ANSIBLE_COMMAND}} ansible-galaxy install -r {{.TASK_NODEJS_ANSIBLE_ROLES_REQUIREMENTS}} --roles-path .config/nodejs/roles"
      - cmd: echo "🎉 Install roles phase completed successfully"
        silent: true

  install:
    desc: |
      ℹ️ Description:
        Installs Node.js using Ansible automation

      🔧 Variables:
        - TASK_NODEJS_ANSIBLE_CMD: Ansible command path
        - TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE: Ansible playbook location
        - TASK_NODEJS_MAJOR_VERSION: Major version of Node.js to install (default: 20.x)

      🔐 Preconditions:
        - Dependencies must be installed
        - Roles must be installed

      🔄 Execution:
        Runs Ansible playbook for Node.js installation
    status:
      - command -v node &> /dev/null
    preconditions:
      - sh: "test -f {{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE}}"
        msg: "❌ Playbook file not found at {{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE}}"
    cmds:
      - cmd: echo "🔄 Starting nodejs installation phase"
        silent: true
      - defer: { task: cleanup }
      - task: install:roles
      - |
        {{.TASK_ANSIBLE_COMMAND}} ansible-playbook \
          -i {{.TASK_NODEJS_ANSIBLE_INVENTORY_TARGET}}, \
          -c local \
          -e "nodejs_version={{.TASK_NODEJS_MAJOR_VERSION}}" \
          {{.TASK_NODEJS_ANSIBLE_PLAYBOOK_FILE}}
      - cmd: echo "🎉 Node.js installation phase completed successfully"
        silent: true

  cleanup:
    internal: true
    cmds:
      - cmd: echo "🔄 Starting cleanup phase"
        silent: true
      - rm -rf .config/nodejs/roles
      - rm -rf {{.TASK_NODEJS_VENV_DIR}}
      - cmd: echo "🎉 Cleanup phase completed successfully"
        silent: true
