title = "Gitleaks Configuration"

# Extend the default configuration
[extend]
useDefault = true

# Global configuration to ignore specific files
[allowlist]
description = "Files to ignore for secrets detection"
paths = [
  '''.*/sealed-secrets\.yaml''',
  '''.*/secrets\.yaml'''
]
