---
version: "3"

includes:
  tests:copier:
    taskfile: ../tests/copier/Taskfile.yml

tasks:
  plan:
    desc: Run project-specific plan tasks
    cmds:
      - cmd: echo "Running project-specific plan tasks..."
        silent: true

  code:
    desc: Run project-specific code tasks
    cmds:
      - cmd: echo "Running project-specific code tasks..."
        silent: true

  build:
    desc: Run project-specific build tasks
    cmds:
      - cmd: echo "Running project-specific build tasks..."
        silent: true
      - task: :docker-ce:build
        vars:
          TASK_DOCKER_CE_IMAGE_TAG:
            sh: |
                if [ -f "VERSION" ]; then
                  echo $(cat VERSION)
                fi

  test:
    desc: Run project-specific test tasks
    cmds:
      - cmd: echo "Running project-specific test tasks..."
        silent: true
      - task: tests:copier

  test:tdd:
    desc: Run project-specific TDD test tasks
    cmds:
      - cmd: echo "Running project-specific TDD test tasks..."
        silent: true

  release:
    desc: Run project-specific release tasks
    cmds:
      - cmd: echo "Running project-specific release tasks..."
        silent: true
      - task: :docker-ce:build
        vars:
          TASK_DOCKER_CE_IMAGE_TAG:
            sh: |
                if [ -f "VERSION" ]; then
                  echo $(cat VERSION)
                fi
      - task: :docker-ce:push
        vars:
          TASK_DOCKER_CE_PUSH:
            sh: |
                if [[ "{{.TASK_DEVSECOPS_RELEASE_CURRENT_BRANCH}}" == "{{.TASK_DEVSECOPS_RELEASE_DEFAULT_BRANCH}}" ]]; then
                  echo "true"
                  exit 0
                fi
                echo "false"
          TASK_DOCKER_CE_IMAGE_TAG:
            sh: |
                if [ -f "VERSION" ]; then
                  echo $(cat VERSION)
                fi

  deploy:
    desc: Run project-specific deploy tasks
    cmds:
      - cmd: echo "Running project-specific deploy tasks..."
        silent: true

  operate:
    desc: Run project-specific operate tasks
    cmds:
      - cmd: echo "Running project-specific operate tasks..."
        silent: true

  monitor:
    desc: Run project-specific monitor tasks
    cmds:
      - cmd: echo "Running project-specific monitor tasks..."
        silent: true

  feedback:
    desc: Run project-specific feedback tasks
    cmds:
      - cmd: echo "Running project-specific feedback tasks..."
        silent: true
