---
version: "3"

vars:
  TASK_DOCKER_CE_IMAGE_NAME: "registry.gitlab.com/digital-commons/devsecops/tools/the-devsecops-plugin"
  TASK_DOCKER_CE_DOCKERFILE: ".config/devcontainer/ubuntu/Dockerfile"

tasks:
  plan:
    desc: Run project-specific plan tasks
    cmds:
      - cmd: echo "🚀 Starting project plan phase"
        silent: true
      - cmd: echo "✅ Project Plan phase completed successfully"
        silent: true

  code:
    desc: Run project-specific code tasks
    cmds:
      - cmd: echo "🚀 Starting project code phase"
        silent: true
      - cmd: echo "✅ Project Code phase completed successfully"
        silent: true

  build:
    desc: Run project-specific build tasks
    cmds:
      - cmd: echo "🚀 Starting project build phase"
        silent: true
      - task: :docker-ce:build
        vars:
          TASK_DOCKER_CE_IMAGE_NAME: "{{.TASK_DOCKER_CE_IMAGE_NAME}}"
          TASK_DOCKER_CE_DOCKERFILE: "{{.TASK_DOCKER_CE_DOCKERFILE}}"
          TASK_DOCKER_CE_IMAGE_TAG:
            sh: |
              if [ -f "VERSION" ]; then
                echo $(cat VERSION)
              fi
      - cmd: echo "✅ Project Build phase completed successfully"
        silent: true

  test:
    desc: Run project-specific test tasks
    cmds:
      - cmd: echo "🚀 Starting project test phase"
        silent: true
      - task: test:tdd
      - cmd: echo "✅ Project Test phase completed successfully"
        silent: true

  test:tdd:
    desc: Run project-specific TDD test tasks
    cmds:
      - cmd: echo "🚀 Starting project TDD test phase"
        silent: true
      - task: :deploy
      - task: :codeceptjs
        vars:
          TASK_CODECEPTJS_GREP: "{{.TASK_CODECEPTJS_GREP}}"
          TASK_CODECEPTJS_CONFIG: "project/plugin/tests/e2e/codeceptjs/codecept.conf.js"
      - cmd: echo "✅ Project TDD test phase completed successfully"
        silent: true

  test:copier:
    desc: Run project-specific copier test tasks
    cmds:
      - cmd: echo "🚀 Starting project copier test phase"
        silent: true
      - task: :codeceptjs
        vars:
          TASK_CODECEPTJS_GREP: "@copier"
          TASK_CODECEPTJS_ENABLED: "true"
          TASK_CODECEPTJS_CONFIG: "project/plugin/tests/e2e/codeceptjs/codecept.conf.js"
      - cmd: echo "✅ Project copier test phase completed successfully"
        silent: true

  release:
    desc: Run project-specific release tasks
    deps:
      - task: build
        vars:
          TASK_DOCKER_CE_IMAGE_TAG:
            sh: |
              if [ -f "VERSION" ]; then
                echo $(cat VERSION)
              fi
    cmds:
      - cmd: echo "🚀 Starting project release phase"
        silent: true
      - task: :docker-ce:push
        vars:
          TASK_DOCKER_CE_PUSH:
            sh: |
              if [ "{{.TASK_DEVSECOPS_RELEASE_CURRENT_BRANCH}}" = "{{.TASK_DEVSECOPS_RELEASE_DEFAULT_BRANCH}}" ]; then
                echo true
              else
                echo false
              fi
          TASK_DOCKER_CE_IMAGE_TAG:
            sh: |
              if [ -f "VERSION" ]; then
                echo $(cat VERSION)
              fi
          TASK_DOCKER_CE_IMAGE_NAME: "{{.TASK_DOCKER_CE_IMAGE_NAME}}"
      - cmd: echo "✅ Project Release phase completed successfully"
        silent: true

  deploy:
    desc: Run project-specific deploy tasks
    cmds:
      - cmd: echo "🚀 Starting project deploy phase"
        silent: true
      - cmd: echo "✅ Project Deploy phase completed successfully"
        silent: true

  operate:
    desc: Run project-specific operate tasks
    cmds:
      - cmd: echo "🚀 Starting project operate phase"
        silent: true
      - cmd: echo "✅ Project Operate phase completed successfully"
        silent: true

  monitor:
    desc: Run project-specific monitor tasks
    cmds:
      - cmd: echo "🚀 Starting project monitor phase"
        silent: true
      - cmd: echo "✅ Project Monitor phase completed successfully"
        silent: true

  feedback:
    desc: Run project-specific feedback tasks
    cmds:
      - cmd: echo "🚀 Starting project feedback phase"
        silent: true
      - cmd: echo "✅ Project Feedback phase completed successfully"
        silent: true
