---
version: "3"

vars:
  TASK_COPIER_ENABLED: '{{.TASK_COPIER_ENABLED | default "true"}}'
  TASK_COPIER_CLI_OPTS: '{{.TASK_COPIER_CLI_OPTS | default ""}}'
  TASK_COPIER_REQUIREMENTS_FILE: '{{.TASK_COPIER_REQUIREMENTS_FILE | default ".config/copier/requirements.txt"}}'
  TASK_COPIER_PYTHON_VERSION_PATH: '{{.TASK_COPIER_PYTHON_VERSION_PATH | default ".config/python/.python-version"}}'
  TASK_COPIER_PYTHON_VERSION:
    sh: |
      if [ -n "${TASK_COPIER_PYTHON_VERSION:-}" ]; then
        echo "${TASK_COPIER_PYTHON_VERSION}"
      else
        cat {{.TASK_COPIER_PYTHON_VERSION_PATH}}
      fi
  TASK_COPIER_VERSION:
    sh: |
      if [ -n "${TASK_COPIER_VERSION:-}" ]; then
        echo "${TASK_COPIER_VERSION}"
      else
        cat {{.TASK_COPIER_REQUIREMENTS_FILE}}
      fi
  TASK_COPIER_COMMAND:
    sh: |
      if [ -n "${TASK_COPIER_COMMAND:-}" ]; then
        echo "${TASK_COPIER_COMMAND}"
      else
        echo "uvx --python {{.TASK_COPIER_PYTHON_VERSION}} --from {{.TASK_COPIER_VERSION}} copier"
      fi

tasks:
  default:
    interactive: true
    desc: |
      ℹ️ Description:
        Run Copier with specified options.

      🔧 Variables:
        - TASK_COPIER_COMMAND: Command to run Copier
        - TASK_COPIER_CLI_OPTS: Additional command line options
          Default: ""

      🔄 Execution:
        Runs Copier with the provided arguments

      📝 Note:
        Use CLI_ARGS to pass additional arguments to Copier
    cmds:
      - cmd: echo "🔄 Running Copier with specified options"
        silent: true
      - "{{.TASK_COPIER_COMMAND}} {{.TASK_COPIER_CLI_OPTS}} {{.CLI_ARGS}}"
      - cmd: echo '🎉 Copier run completed successfully.'
        silent: true

  update:
    desc: |
      ℹ️ Description:
        Updates the project using Copier with a specific answers file.

      🔧 Variables:
        - TASK_COPIER_ANSWER_FILE: Path to the Copier answers file (e.g., .config/devsecops/.copier-answers.yml)
          Required: Yes
        - TASK_COPIER_COMMAND: Command to run Copier
        - TASK_COPIER_CLI_OPTS: Additional command line options
          Default: ""

      🔐 Preconditions:
        - The 'install' task must be completed
        - The TASK_COPIER_ANSWER_FILE variable must be provided

      🔄 Execution:
        Runs 'copier update -a <TASK_COPIER_ANSWER_FILE>'

      📝 Note:
        Provide the answers file path via 'task update TASK_COPIER_ANSWER_FILE=path/to/answers.yml'
    preconditions:
      - sh: test -n "{{.TASK_COPIER_ANSWER_FILE}}"
        msg: "❌ Error: TASK_COPIER_ANSWER_FILE variable is required. Usage: task update TASK_COPIER_ANSWER_FILE=path/to/answers.yml"
    cmds:
      - cmd: echo "🔄 Updating Copier project using {{.TASK_COPIER_ANSWER_FILE}}"
        silent: true
      - "{{.TASK_COPIER_COMMAND}} update {{.TASK_COPIER_CLI_OPTS}} --answers-file {{.TASK_COPIER_ANSWER_FILE}}"
      - cmd: echo "🎉 Copier update completed successfully."
        silent: true
