---
version: "3"

vars:
  TASK_YAMLLINT_ENABLED: '{{.TASK_YAMLLINT_ENABLED | default "true"}}'
  TASK_YAMLLINT_VIRTUALENV: '{{.TASK_YAMLLINT_VIRTUALENV | default "./venv/yamllint"}}'
  TASK_YAMLLINT_COMMAND: '{{.TASK_YAMLLINT_COMMAND | default "./venv/yamllint/bin/yamllint"}}'
  TASK_YAMLLINT_CONFIG_FULL_PATH: '{{.TASK_YAMLLINT_CONFIG_FULL_PATH | default ".config/yamllint/config.yml"}}'
  TASK_YAMLLINT_CLI_OPTS: '{{.TASK_YAMLLINT_CLI_OPTS | default "--strict"}}'
  TASK_YAMLLINT_PATH_TO_LINT: '{{.TASK_YAMLLINT_PATH_TO_LINT | default "."}}'

tasks:
  default:
    deps: [install]
    desc: Lint YAML files using yamllint.
    summary: |
      🏷️ Description:
        Executes yamllint to ensure YAML files adhere to specified syntax standards.

      🔧 Variables:
        - TASK_YAMLLINT_VIRTUALENV: Path to the virtual environment. Default: "./venv/yamllint"
        - TASK_YAMLLINT_COMMAND: Command to run yamllint. Default: "./venv/yamllint/bin/yamllint"
        - TASK_YAMLLINT_CONFIG_FULL_PATH: Full path to the yamllint configuration file. Default: ".config/yamllint/config.yml"
        - TASK_YAMLLINT_CLI_OPTS: Command line options for yamllint. Default: "--strict"
        - TASK_YAMLLINT_PATH_TO_LINT: Path to the files to be linted. Default: "."

      🔐 Preconditions:
        - The 'install' task must have been successfully executed.
        - A yamllint configuration file must exist at the specified location.

      🔄 Execution:
        Runs yamllint with the specified options and configuration on the designated files.

      📝 Note:
        This task should be executed after any modifications to YAML files to maintain consistent formatting.
    cmds:
      - cmd: echo "🔄 Starting yamllint phase"
        silent: true
      - "{{.TASK_YAMLLINT_COMMAND}} {{.TASK_YAMLLINT_CLI_OPTS}} -c {{.TASK_YAMLLINT_CONFIG_FULL_PATH}} {{.TASK_YAMLLINT_PATH_TO_LINT}}"
      - cmd: echo "🎉 All files correctly linted with yamllint!"
        silent: true

  install:
    desc: Set up yamllint in a virtual environment.
    summary: |
      🎯 Description:
        Configures yamllint and its dependencies within a controlled virtual environment.

      🔧 Variables:
        - TASK_YAMLLINT_PYTHON_VERSION_FILE: Path to the file specifying the Python version.
          Default: ".config/python/.python-version"
          Example content: "3.11"
        - TASK_YAMLLINT_REQUIREMENTS_FILE: Path to the file listing required packages.
          Default: ".config/yamllint/requirements.txt"
          Example content: "yamllint==1.32.0"
        - TASK_YAMLLINT_VIRTUALENV: Location of the virtual environment for yamllint.
          Default: "./venv/yamllint"

      🔐 Preconditions:
        - A Python version file must exist at the specified location.
          Example content: "3.11"
        - An active internet connection is required to download yamllint and its dependencies.

      🔄 Execution:
        1. Creates a new Python virtual environment using the version specified in TASK_YAMLLINT_PYTHON_VERSION_FILE.
        2. Installs yamllint and its dependencies using the TASK_YAMLLINT_REQUIREMENTS_FILE.
        3. Verifies the installation by checking the installed yamllint version.

      📝 Note:
        Ensure the Python version file specifies a version compatible with yamllint and its dependencies.
    preconditions:
      - sh: test -f {{.TASK_YAMLLINT_PYTHON_VERSION_FILE}}
        msg: |
          Error: missing file {{.TASK_YAMLLINT_PYTHON_VERSION_FILE}}.
          Please create it as follows:
          ```bash
          mkdir -p $(dirname "{{.TASK_YAMLLINT_PYTHON_VERSION_FILE}}")
          echo "3.11" > {{.TASK_YAMLLINT_PYTHON_VERSION_FILE}}
          ```
    vars:
      TASK_YAMLLINT_PYTHON_VERSION_FILE: '{{.TASK_YAMLLINT_PYTHON_VERSION_FILE | default ".config/python/.python-version"}}'
      TASK_YAMLLINT_REQUIREMENTS_FILE: '{{.TASK_YAMLLINT_REQUIREMENTS_FILE | default ".config/yamllint/requirements.txt"}}'
    status:
      - |
        {{.TASK_YAMLLINT_COMMAND}} --version | grep -q $(awk -F '==' '{print $2}' {{.TASK_YAMLLINT_REQUIREMENTS_FILE}})
    cmds:
      - cmd: echo "🔄 Starting install phase"
        silent: true
      - python$(cut -d '=' -f 2 {{.TASK_YAMLLINT_PYTHON_VERSION_FILE}}) -m venv {{.TASK_YAMLLINT_VIRTUALENV}}
      - "{{.TASK_YAMLLINT_VIRTUALENV}}/bin/pip install -r {{.TASK_YAMLLINT_REQUIREMENTS_FILE}}"
      - cmd: echo "🎉  Yamllint and dependencies are successfully installed in the virtual environment."
        silent: true
