---
version: "3"

vars:
  TASK_YAMLLINT_ENABLED: '{{.TASK_YAMLLINT_ENABLED | default "true"}}'
  TASK_YAMLLINT_CONFIG_FULL_PATH: '{{.TASK_YAMLLINT_CONFIG_FULL_PATH | default ".config/yamllint/config.yml"}}'
  TASK_YAMLLINT_CLI_OPTS: '{{.TASK_YAMLLINT_CLI_OPTS | default "--strict"}}'
  TASK_YAMLLINT_PATH_TO_LINT: '{{.TASK_YAMLLINT_PATH_TO_LINT | default "."}}'
  TASK_YAMLLINT_REQUIREMENTS_FILE: '{{.TASK_YAMLLINT_REQUIREMENTS_FILE | default ".config/yamllint/requirements.txt"}}'
  TASK_YAMLLINT_VERSION:
    sh: |
      if [ -n "${TASK_YAMLLINT_VERSION:-}" ]; then
        echo "${TASK_YAMLLINT_VERSION}"
      else
        cat {{.TASK_YAMLLINT_REQUIREMENTS_FILE}}
      fi
  TASK_YAMLLINT_COMMAND:
    sh: |
      if [ -n "${TASK_YAMLLINT_COMMAND:-}" ]; then
        echo "${TASK_YAMLLINT_COMMAND}"
      else
        echo "uvx --from {{.TASK_YAMLLINT_VERSION}} yamllint"
      fi

tasks:
  default:
    desc: Lint YAML files using yamllint.
    summary: |
      🏷️ Description:
        Executes yamllint to ensure YAML files adhere to specified syntax standards.

      🔧 Variables:
        - TASK_YAMLLINT_CONFIG_FULL_PATH: Full path to the yamllint configuration file. Default: ".config/yamllint/config.yml"
        - TASK_YAMLLINT_CLI_OPTS: Command line options for yamllint. Default: "--strict"
        - TASK_YAMLLINT_PATH_TO_LINT: Path to the files to be linted. Default: "."

      🔐 Preconditions:
        - The 'install' task must have been successfully executed.
        - A yamllint configuration file must exist at the specified location.

      🔄 Execution:
        Runs yamllint with the specified options and configuration on the designated files.

      📝 Note:
        This task should be executed after any modifications to YAML files to maintain consistent formatting.
    cmds:
      - cmd: echo "🔄 Starting yamllint phase"
        silent: true
      - "{{.TASK_YAMLLINT_COMMAND}} {{.TASK_YAMLLINT_CLI_OPTS}} -c {{.TASK_YAMLLINT_CONFIG_FULL_PATH}} {{.TASK_YAMLLINT_PATH_TO_LINT}}"
      - cmd: echo "🎉 All files correctly linted with yamllint!"
        silent: true
