---
version: "3"

vars:
  TASK_DEV_ENABLED: '{{.OVERRIDE_TASK_DEV_ENABLED | default "true"}}'

tasks:
  setup-environment:
    desc: Configure the development environment.
    cmds:
      - task: ansible
      - task: bun
      - task: docker-ce
      - task: go
      - task: helm
      - task: k3d
      - task: kubectl
      - task: kubeseal
      - task: nodejs
      - task: podman

  ansible:
    internal: true
    status:
      - test "{{.TASK_ANSIBLE_ENABLED}}" = "false"
    cmds:
      - task: :ansible:install

  bun:
    internal: true
    status:
      - test "{{.TASK_BUN_ENABLED}}" = "false"
    cmds:
      - task: :bun:install

  docker-ce:
    internal: true
    status:
      - test "{{.TASK_DOCKER_CE_ENABLED}}" = "false"
    cmds:
      - task: :docker-ce:install

  go:
    internal: true
    status:
      - test "{{.TASK_GO_ENABLED}}" = "false"
    cmds:
      - task: :go:install

  helm:
    internal: true
    status:
      - test "{{.TASK_HELM_ENABLED}}" = "false"
    cmds:
      - task: :helm:install

  k3d:
    internal: true
    status:
      - test "{{.TASK_K3D_ENABLED}}" = "false"
    cmds:
      - task: :k3d:install

  kubectl:
    internal: true
    status:
      - test "{{.TASK_KUBECTL_ENABLED}}" = "false"
    cmds:
      - task: :kubectl:install

  kubeseal:
    internal: true
    status:
      - test "{{.TASK_KUBESEAL_ENABLED}}" = "false"
    cmds:
      - task: :kubeseal:install

  nodejs:
    internal: true
    status:
      - test "{{.TASK_NODEJS_ENABLED}}" = "false"
    cmds:
      - task: :nodejs:install

  podman:
    internal: true
    status:
      - test "{{.TASK_PODMAN_ENABLED}}" = "false"
    cmds:
      - task: :podman:install
