---
version: "3"

tasks:
  setup-environment:
    desc: Configure the development environment.
    cmds:
      - cmd: |
          if [[ "{{.TASK_BUN_ENABLED}}" == "true" ]]; then
            echo "🔍 Running bun..."
            task bun:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping bun (disabled via TASK_BUN_ENABLED=false)"
          fi
        silent: true
      - cmd: |
          if [[ "{{.TASK_COPIER_ENABLED}}" == "true" ]]; then
            echo "🔍 Running copier..."
            task copier:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping copier (disabled via TASK_COPIER_ENABLED=false)"
          fi
        silent: true
      - cmd: |
          if [[ "{{.TASK_DOCKER_CE_ENABLED}}" == "true" ]]; then
            echo "🔍 Running docker-ce..."
            task docker-ce:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping docker-ce (disabled via TASK_DOCKER_CE_ENABLED=false)"
          fi
        silent: true
      - cmd: |
          if [[ "{{.TASK_NODEJS_ENABLED}}" == "true" ]]; then
            echo "🔍 Running nodejs..."
            task nodejs:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping nodejs (disabled via TASK_NODEJS_ENABLED=false)"
          fi
        silent: true
