---
version: "3"

vars:
  TASK_DEV_ENABLED: '{{.OVERRIDE_TASK_DEV_ENABLED | default "true"}}'

tasks:
  setup-environment:
    desc: Configure the development environment.
    cmds:
      - cmd: |
          if [[ "{{.TASK_BUN_ENABLED}}" == "true" ]]; then
            echo "🔄 Running bun..."
            task {{.TASK_FLAGS}} bun:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping bun (disabled via TASK_BUN_ENABLED=false)"
          fi
        silent: true
      - cmd: |
          if [[ "{{.TASK_COPIER_ENABLED}}" == "true" ]]; then
            echo "🔄 Running copier..."
            task {{.TASK_FLAGS}} copier:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping copier (disabled via TASK_COPIER_ENABLED=false)"
          fi
        silent: true
      - cmd: |
          if [[ "{{.TASK_DOCKER_CE_ENABLED}}" == "true" ]]; then
            echo "🔄 Running docker-ce..."
            task {{.TASK_FLAGS}} docker-ce:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping docker-ce (disabled via TASK_DOCKER_CE_ENABLED=false)"
          fi
        silent: true
      - cmd: |
          if [[ "{{.TASK_PODMAN_ENABLED}}" == "true" ]]; then
            echo "🔄 Running podman..."
            task {{.TASK_FLAGS}} podman:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping podman (disabled via TASK_PODMAN_ENABLED=false)"
          fi
        silent: true
      - cmd: |
          if [[ "{{.TASK_NODEJS_ENABLED}}" == "true" ]]; then
            echo "🔄 Running nodejs..."
            task {{.TASK_FLAGS}} nodejs:install
            echo "{{.TASK_SEPARATOR}}"
          else
            echo "⚠️ Skipping nodejs (disabled via TASK_NODEJS_ENABLED=false)"
          fi
        silent: true
