---
version: "3"

vars:
  TASK_LIZARD_ENABLED: '{{.TASK_LIZARD_ENABLED | default "true"}}'
  TASK_LIZARD_CLI_OPTS: '{{.TASK_LIZARD_CLI_OPTS | default ""}}'
  TASK_LIZARD_PATH_TO_ANALYSE: '{{.TASK_LIZARD_PATH_TO_ANALYSE | default "."}}'
  TASK_LIZARD_REQUIREMENTS_FILE: '{{.TASK_LIZARD_REQUIREMENTS_FILE | default ".config/lizard/requirements.txt"}}'
  TASK_LIZARD_PYTHON_VERSION_PATH: '{{.TASK_LIZARD_PYTHON_VERSION_PATH | default ".config/python/.python-version"}}'
  TASK_LIZARD_PYTHON_VERSION:
    sh: |
      if [ -n "${TASK_LIZARD_PYTHON_VERSION:-}" ]; then
        echo "${TASK_LIZARD_PYTHON_VERSION}"
      else
        cat {{.TASK_LIZARD_PYTHON_VERSION_PATH}}
      fi
  TASK_LIZARD_VERSION:
    sh: |
      if [ -n "${TASK_LIZARD_VERSION:-}" ]; then
        echo "${TASK_LIZARD_VERSION}"
      else
        cat {{.TASK_LIZARD_REQUIREMENTS_FILE}}
      fi
  TASK_LIZARD_COMMAND:
    sh: |
      if [ -n "${TASK_LIZARD_COMMAND:-}" ]; then
        echo "${TASK_LIZARD_COMMAND}"
      else
        echo "uvx --python {{.TASK_LIZARD_PYTHON_VERSION}} --from {{.TASK_LIZARD_VERSION}} lizard"
      fi

tasks:
  default:
    desc: Analyze code complexity with Lizard.
    summary: |
      ℹ️ Description:
        Executes Lizard to analyse code complexity and maintainability.

      🔧 Variables:
        - TASK_LIZARD_VERSION: Lizard version
        - TASK_LIZARD_CLI_OPTS: Command-line options for Lizard
        - TASK_LIZARD_PATH_TO_ANALYSE: Path to analyse

      🔄 Execution:
        Runs Lizard with specified options on designated files

      📝 Note:
        Execute after code modifications to maintain quality standards
    status:
      - test "{{.TASK_LIZARD_ENABLED}}" = "false"
    cmds:
      - cmd: echo "🔄 Starting lizard analysis phase"
        silent: true
      - |
        # Build exclusion arguments from .gitignore, handling spaces in patterns
        EXCLUDE_ARGS=""
        while IFS= read -r line; do
          [ -z "$line" ] && continue
          case "$line" in \#*) continue ;; esac
          if echo "$line" | grep -q '\.'; then
            EXCLUDE_ARGS="$EXCLUDE_ARGS -x\"$line\""
          else
            EXCLUDE_ARGS="$EXCLUDE_ARGS -x\"./$line/*\""
          fi
        done < .gitignore
        eval {{.TASK_LIZARD_COMMAND}} $EXCLUDE_ARGS {{.TASK_LIZARD_CLI_OPTS}} {{.TASK_LIZARD_PATH_TO_ANALYSE}}
      - cmd: echo "🎉 Lizard analysis phase completed successfully"
        silent: true
