---
version: "3"

vars:
  TASK_LIZARD_ENABLED: '{{.TASK_LIZARD_ENABLED | default "true"}}'
  TASK_LIZARD_CLI_OPTS: '{{.TASK_LIZARD_CLI_OPTS | default ""}}'
  TASK_LIZARD_VERSION:
    sh: |
      if [ -n "${TASK_LIZARD_VERSION:-}" ]; then
        echo "${TASK_LIZARD_VERSION}"
      else
        cat .config/lizard/requirements.txt
      fi
  TASK_LIZARD_PATH_TO_ANALYSE: '{{.TASK_LIZARD_PATH_TO_ANALYSE | default "."}}'

tasks:
  default:
    desc: Analyze code complexity with Lizard.
    summary: |
      ℹ️ Description:
        Executes Lizard to analyse code complexity and maintainability.

      🔧 Variables:
        - TASK_LIZARD_VERSION: Lizard version
        - TASK_LIZARD_CLI_OPTS: Command-line options for Lizard
        - TASK_LIZARD_PATH_TO_ANALYSE: Path to analyse

      🔄 Execution:
        Runs Lizard with specified options on designated files

      📝 Note:
        Execute after code modifications to maintain quality standards
    status:
      - test "{{.TASK_LIZARD_ENABLED}}" = "false"
    cmds:
      - cmd: echo "🔄 Starting lizard analysis phase"
        silent: true
      - |
        uvx {{.TASK_LIZARD_VERSION}} $(grep -v '^#' .gitignore | grep -v '^$' | awk '{if ($0 ~ /\./) print "-x"$0; else print "-x./"$0"/*"}' | tr '\n' ' ') {{.TASK_LIZARD_CLI_OPTS}} {{.TASK_LIZARD_PATH_TO_ANALYSE}}
      - cmd: echo "🎉 Lizard analysis phase completed successfully"
        silent: true
