---
version: "3"

vars:
  TASK_COMMITIZEN_ENABLED: '{{.TASK_COMMITIZEN_ENABLED | default "true"}}'
  TASK_COMMITIZEN_VIRTUALENV: '{{.TASK_COMMITIZEN_VIRTUALENV | default "./venv/commitizen"}}'
  TASK_COMMITIZEN_COMMAND: '{{.TASK_COMMITIZEN_COMMAND | default "./venv/commitizen/bin/cz"}}'
  TASK_COMMITIZEN_CONFIG_FULL_PATH: '{{.TASK_COMMITIZEN_CONFIG_FULL_PATH | default ".config/commitizen/cz.yaml"}}'
  TASK_COMMITIZEN_CLI_OPTS: '{{.TASK_COMMITIZEN_CLI_OPTS | default ""}}'
  TASK_COMMITIZEN_CLI_CHECK_OPTS: '{{.TASK_COMMITIZEN_CLI_CHECK_OPTS | default "--rev-range origin/main..HEAD"}}'
  TASK_COMMITIZEN_PYTHON_VERSION_FILE: '{{.TASK_COMMITIZEN_PYTHON_VERSION_FILE | default ".config/python/.python-version"}}'
  TASK_COMMITIZEN_REQUIREMENTS_FILE: '{{.TASK_COMMITIZEN_REQUIREMENTS_FILE | default ".config/commitizen/requirements.txt"}}'
  TASK_COMMITIZEN_BUMP_DRY_RUN: '{{.TASK_COMMITIZEN_BUMP_DRY_RUN | default "false"}}'
  TASK_COMMITIZEN_BUMP_YES: '{{.TASK_COMMITIZEN_BUMP_YES | default "false"}}'
  TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY: '{{.TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY | default "true"}}'
  TASK_COMMITIZEN_BUMP_NO_RAISE: '{{.TASK_COMMITIZEN_BUMP_NO_RAISE | default "21"}}'
  TASK_COMMITIZEN_BUMP_CHANGELOG: '{{.TASK_COMMITIZEN_BUMP_CHANGELOG | default "false"}}'
  TASK_COMMITIZEN_BUMP_PRERELEASE: '{{.TASK_COMMITIZEN_BUMP_PRERELEASE | default ""}}'
  TASK_COMMITIZEN_BUMP_DEV_RELEASE: '{{.TASK_COMMITIZEN_BUMP_DEV_RELEASE | default ""}}'
  TASK_COMMITIZEN_DEFAULT_BRANCH: '{{.TASK_COMMITIZEN_DEFAULT_BRANCH | default "main"}}'
  TASK_COMMITIZEN_RELEASE_BRANCH_PATTERN: '{{.TASK_COMMITIZEN_RELEASE_BRANCH_PATTERN | default "^release/"}}'
  TASK_COMMITIZEN_GIT_CURRENT_BRANCH:
    sh: |
      if [ -n "$CI_COMMIT_REF_NAME" ]; then
        echo "$CI_COMMIT_REF_NAME"
      elif [ -n "$GITHUB_REF_NAME" ]; then
        echo "$GITHUB_REF_NAME"
      elif [ -n "$GIT_BRANCH" ]; then
        echo "$GIT_BRANCH"
      else
        git rev-parse --abbrev-ref HEAD
      fi

tasks:
  default:
    deps: [install]
    interactive: true
    desc: Run Commitizen for commit message formatting.
    summary: |
      ℹ️ Description:
        Executes commitizen to guide the user through creating a standardized commit message.

      🔧 Variables:
        - TASK_COMMITIZEN_VIRTUALENV: Path to the virtual environment. Default: "./venv/commitizen"
        - TASK_COMMITIZEN_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
        - TASK_COMMITIZEN_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
        - TASK_COMMITIZEN_CLI_OPTS: Command line options for commitizen. Default: ""

      🔐 Preconditions:
        - The 'install' task must have been successfully executed.
        - A commitizen configuration file must exist at the specified location.

      🔄 Execution:
        Runs commitizen with the specified options and configuration for interactive commit message creation.

      📝 Note:
        This task should be executed when creating a new commit.
    cmds:
      - cmd: echo "🔄 Starting Commitizen commit message formatting"
        silent: true
      - "{{.TASK_COMMITIZEN_COMMAND}} --config {{.TASK_COMMITIZEN_CONFIG_FULL_PATH}} {{.TASK_COMMITIZEN_CLI_OPTS}} commit {{.CLI_ARGS}}"
      - cmd: echo '🎉 Commitizen commit message formatting completed.'
        silent: true

  install:
    desc: Set up Commitizen in a virtual environment.
    summary: |
      ℹ️ Description:
        Configures Commitizen and its dependencies within a controlled virtual environment.

      🔧 Variables:
        - TASK_COMMITIZEN_PYTHON_VERSION_FILE: Path to the file specifying the Python version.
          Default: ".config/python/.python-version"
          Example content: "3.11"
        - TASK_COMMITIZEN_REQUIREMENTS_FILE: Path to the file listing required packages.
          Default: ".config/commitizen/requirements.txt"
          Example content: "commitizen==3.28.0"
        - TASK_COMMITIZEN_VIRTUALENV: Location of the virtual environment for Commitizen.
          Default: "./venv/commitizen"

      🔐 Preconditions:
        - Python must be installed on the system.
        - A Python version file must exist at the specified location.
        - An active internet connection is required to download Commitizen and its dependencies.

      🔄 Execution:
        1. Creates a new Python virtual environment using the version specified in TASK_COMMITIZEN_PYTHON_VERSION_FILE.
        2. Installs Commitizen and its dependencies using the TASK_COMMITIZEN_REQUIREMENTS_FILE.
        3. Verifies the installation by checking the installed Commitizen version.

      📝 Note:
        Ensure the Python version file specifies a version compatible with Commitizen and its dependencies.
    preconditions:
      - sh: command -v python3 >/dev/null 2>&1
        msg: "❌ Error: Python is not installed. Please install Python before proceeding."
      - sh: test -f {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}
        msg: |
          ❌ Error: missing file {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}.
          Please create it as follows:
          ```bash
          mkdir -p $(dirname "{{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}")
          echo "3.11" > {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}
          ```
    status:
      - |
        {{.TASK_COMMITIZEN_COMMAND}} version | grep -q $(awk -F '==' '{print $2}' {{.TASK_COMMITIZEN_REQUIREMENTS_FILE}})
    cmds:
      - cmd: echo "🔄 Setting up Commitizen virtual environment"
        silent: true
      - python$(cut -d '=' -f 2 {{.TASK_COMMITIZEN_PYTHON_VERSION_FILE}}) -m venv {{.TASK_COMMITIZEN_VIRTUALENV}}
      - "{{.TASK_COMMITIZEN_VIRTUALENV}}/bin/pip install -r {{.TASK_COMMITIZEN_REQUIREMENTS_FILE}}"
      - cmd: echo '🎉 Commitizen and dependencies installed successfully.'
        silent: true

  check:
    deps: [install]
    desc: Verify commit messages with Commitizen.
    summary: |
      ℹ️ Description:
        Automatically verifies commits using Commitizen rules.

      🔧 Variables:
        - TASK_COMMITIZEN_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
        - TASK_COMMITIZEN_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
        - TASK_COMMITIZEN_CLI_OPTS: Additional command line options for commitizen. Default: ""
        - TASK_COMMITIZEN_CLI_CHECK_OPTS: Options specific to the check command. Default: "--rev-range origin/main..HEAD"

      🔐 Preconditions:
        - The 'install' task must have been successfully executed.
        - A commitizen configuration file must exist at the specified location.

      🔄 Execution:
        Runs the commitizen check command with the specified configuration and options.

      📝 Note:
        This task verifies that commit messages conform to the Commitizen standards.
        The default behaviour checks commits from main to HEAD, but this can be customised
        by modifying the TASK_COMMITIZEN_CLI_CHECK_OPTS variable.
    status:
      - test "{{.TASK_COMMITIZEN_ENABLED}}" = "false"
    vars:
      COMMITIZEN_CHECK_COMMAND:
        sh: echo "{{.TASK_COMMITIZEN_COMMAND}} --config {{.TASK_COMMITIZEN_CONFIG_FULL_PATH}} {{.TASK_COMMITIZEN_CLI_OPTS}} check {{.TASK_COMMITIZEN_CLI_CHECK_OPTS}}"
    cmds:
      - cmd: echo "🔄 Running Commitizen check"
        silent: true
      - cmd: echo "{{.COMMITIZEN_CHECK_COMMAND}}"
        silent: true
      - cmd: |
          if {{.COMMITIZEN_CHECK_COMMAND}}; then
            echo "🎉 All commits successfully verified with Commitizen!"
          else
            exit_code=$?
            if [ $exit_code -eq 3 ]; then
              echo "⚠️  Warning: No commits found in the specified range to verify."
            else
              echo "❌ Commitizen check failed with exit code $exit_code"
              exit $exit_code
            fi
          fi
      - cmd: echo '🎉 Commitizen check completed.'
        silent: true

  bump:
    deps: [install]
    desc: Increment version based on commit history.
    summary: |
      ℹ️ Description:
        Increments the version number based on the commit history.

      🔧 Variables:
        - TASK_COMMITIZEN_COMMAND: Command to run commitizen. Default: "./venv/commitizen/bin/cz"
        - TASK_COMMITIZEN_CONFIG_FULL_PATH: Path to the commitizen configuration file. Default: ".config/commitizen/cz.yaml"
        - TASK_COMMITIZEN_CLI_OPTS: Additional command line options for commitizen. Default: ""
        - TASK_COMMITIZEN_BUMP_DRY_RUN: Whether to perform a dry run. Default: true
        - TASK_COMMITIZEN_BUMP_YES: Whether to automatically confirm prompts. Default: false
        - TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY: Whether to check consistency before bumping. Default: true
        - TASK_COMMITIZEN_BUMP_NO_RAISE: Comma-separated error codes that won't raise an error. Default: "21"
        - TASK_COMMITIZEN_BUMP_CHANGELOG: Whether to update the changelog when bumping. Default: false
        - TASK_COMMITIZEN_BUMP_PRERELEASE: Prerelease identifier (e.g., "alpha", "beta"). Default: ""
        - TASK_COMMITIZEN_BUMP_DEV_RELEASE: Development release identifier. Default: ""

      🔐 Preconditions:
        - The 'install' task must have been successfully executed.
        - A commitizen configuration file must exist at the specified location.

      🔄 Execution:
        Runs the commitizen bump command with the specified configuration and options.

      📝 Note:
        This task increments the version number based on the commit history.
        Use TASK_COMMITIZEN_BUMP_DRY_RUN=false to apply changes, TASK_COMMITIZEN_BUMP_YES=false to enable confirmations,
        and TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY=false to skip consistency checks if needed.
        Set TASK_COMMITIZEN_BUMP_NO_RAISE to a comma-separated list of error codes to ignore specific errors,
        e.g., TASK_COMMITIZEN_BUMP_NO_RAISE=21 to ignore the "Nothing to commit" error.
        Use TASK_COMMITIZEN_BUMP_PRERELEASE and TASK_COMMITIZEN_BUMP_DEV_RELEASE for managing pre-releases and development versions.
    vars:
      BUMP_OPTIONS:
        sh: |
          options=(
            {{if eq .TASK_COMMITIZEN_BUMP_YES "true"}}"--yes"{{end}}
            {{if eq .TASK_COMMITIZEN_BUMP_DRY_RUN "true"}}"--dry-run"{{end}}
            {{if eq .TASK_COMMITIZEN_BUMP_CHECK_CONSISTENCY "true"}}"--check-consistency"{{end}}
            {{if eq .TASK_COMMITIZEN_BUMP_CHANGELOG "true"}}"--changelog"{{end}}
          )

          if [[ "{{.TASK_COMMITIZEN_GIT_CURRENT_BRANCH}}" =~ {{.TASK_COMMITIZEN_RELEASE_BRANCH_PATTERN}} ]] || [ -n "{{.TASK_COMMITIZEN_BUMP_PRERELEASE}}" ]; then
            options+=("--prerelease")
          elif [[ "{{.TASK_COMMITIZEN_GIT_CURRENT_BRANCH}}" != "{{.TASK_COMMITIZEN_DEFAULT_BRANCH}}" ]] || [ -n "{{.TASK_COMMITIZEN_BUMP_DEV_RELEASE}}" ]; then
            options+=("--devrelease" "$(date +%Y%m%d%H%M%S)")
          fi

          echo "${options[@]}"
      CLI_OPTIONS:
        sh: |
          options=({{.TASK_COMMITIZEN_CLI_OPTS}})
          if [ -n "{{.TASK_COMMITIZEN_BUMP_NO_RAISE}}" ]; then
            options+=("--no-raise" "{{.TASK_COMMITIZEN_BUMP_NO_RAISE}}")
          fi
          echo "${options[@]}"
      COMMITIZEN_BUMP_COMMAND:
        sh: echo "{{.TASK_COMMITIZEN_COMMAND}} --config {{.TASK_COMMITIZEN_CONFIG_FULL_PATH}} {{.CLI_OPTIONS}} bump {{.BUMP_OPTIONS}}"
    status:
      - test "{{.TASK_COMMITIZEN_ENABLED}}" = "false"
    cmds:
      - cmd: echo "🔄 Running Commitizen version bump"
        silent: true
      - cmd: echo "{{.COMMITIZEN_BUMP_COMMAND}}"
        silent: true
      - cmd: |
          if {{.COMMITIZEN_BUMP_COMMAND}}; then
            echo "🎉 All commits successfully verified with Commitizen!"
          else
            exit_code=$?
            if [ $exit_code -eq 3 ]; then
              echo "⚠️  Warning: No commits found in the specified range to verify."
            else
              echo "❌ Commitizen bump failed with exit code $exit_code"
              exit $exit_code
            fi
          fi
        silent: true
      - cmd: |
          if [ "{{.TASK_COMMITIZEN_BUMP_DRY_RUN}}" = "true" ]; then
            echo "Info : Version bump completed in dry-run mode. No changes were applied."
          else
            echo "🎉 Version bump completed successfully!"
          fi
        silent: true
      - cmd: echo '🎉 Commitizen version bump process completed.'
        silent: true
