exclude = [
  '.*package-lock\.json',
  'file://*',
  'file://charts/',
  'http://localhost',
  'http://proxy',
  'https://dl.k8s.io/release/',
  'https://docker:8001',
  'https://localhost',
  'https://tidelift.com/funding/github/npm/parse-function',
  'tcp://*'
]
