---
version: "3"

vars:
  TASK_GO_ENABLED: '{{.OVERRIDE_TASK_GO_ENABLED | default "true"}}'
  TASK_GO_VENV_DIR: '{{.OVERRIDE_TASK_GO_VENV_DIR | default "./venv/go"}}'
  TASK_GO_ANSIBLE_CMD: '{{.OVERRIDE_TASK_GO_ANSIBLE_CMD | default "./venv/go/bin/ansible-playbook"}}'
  TASK_GO_ANSIBLE_GALAXY_CMD: '{{.OVERRIDE_TASK_GO_ANSIBLE_GALAXY_CMD | default "./venv/go/bin/ansible-galaxy"}}'
  TASK_GO_ANSIBLE_REQUIREMENTS_FILE: '{{.OVERRIDE_TASK_GO_ANSIBLE_REQUIREMENTS_FILE | default ".config/go/requirements.txt"}}'
  TASK_GO_ANSIBLE_ROLES_REQUIREMENTS: '{{.OVERRIDE_TASK_GO_ANSIBLE_ROLES_REQUIREMENTS | default ".config/go/requirements.yml"}}'
  TASK_GO_ANSIBLE_PLAYBOOK_FILE: '{{.OVERRIDE_TASK_GO_ANSIBLE_PLAYBOOK_FILE | default ".config/go/playbook.yml"}}'
  TASK_GO_PYTHON_VERSION_FILE: '{{.OVERRIDE_TASK_GO_PYTHON_VERSION_FILE | default ".config/python/.python-version"}}'
  TASK_GO_ANSIBLE_INVENTORY_TARGET: "localhost" # DevSkim: ignore DS162092
  TASK_GO_VERSION: '{{.OVERRIDE_TASK_GO_VERSION | default "1.24.1"}}'
  TASK_GO_CHECKSUM: '{{.OVERRIDE_TASK_GO_CHECKSUM | default "cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073"}}' # DevSkim: ignore DS173237

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  LANGUAGE: "C.UTF-8"
  ANSIBLE_ROLES_PATH: ".config/go/roles"

tasks:
  install:dependencies:
    desc: |
      ℹ️ Description:
        Sets up Ansible and its dependencies in a dedicated virtual environment

      🔧 Variables:
        - TASK_GO_VENV_DIR: Virtual environment location
        - TASK_GO_ANSIBLE_REQUIREMENTS_FILE: Dependencies file path

      🔐 Preconditions:
        - Python 3.x must be installed
        - Internet connectivity required

      🔄 Execution:
        Creates virtualenv and installs required packages
    preconditions:
      - sh: "command -v python3 >/dev/null 2>&1"
        msg: "❌ Python 3 is not installed"
      - sh: "test -f {{.TASK_GO_PYTHON_VERSION_FILE}}"
        msg: "❌ Python version file not found at {{.TASK_GO_PYTHON_VERSION_FILE}}"
      - sh: "test -f {{.TASK_GO_ANSIBLE_REQUIREMENTS_FILE}}"
        msg: "❌ Requirements file not found at {{.TASK_GO_ANSIBLE_REQUIREMENTS_FILE}}"
    cmds:
      - python$(cut -d '=' -f 2 {{.TASK_GO_PYTHON_VERSION_FILE}}) -m venv {{.TASK_GO_VENV_DIR}}
      - "{{.TASK_GO_VENV_DIR}}/bin/pip install -r {{.TASK_GO_ANSIBLE_REQUIREMENTS_FILE}}"
      - cmd: echo "✅ Dependencies installed successfully"
        silent: true

  install:roles:
    desc: |
      ℹ️ Description:
        Installs required Ansible roles

      🔧 Variables:
        - TASK_GO_ANSIBLE_GALAXY_CMD: Ansible Galaxy command path
        - TASK_GO_ANSIBLE_ROLES_REQUIREMENTS: Roles requirements file path

      🔐 Preconditions:
        - Dependencies must be installed

      🔄 Execution:
        Installs required Ansible roles
    deps: [install:dependencies]
    preconditions:
      - sh: "test -f {{.TASK_GO_ANSIBLE_ROLES_REQUIREMENTS}}"
        msg: "❌ Roles requirements file not found at {{.TASK_GO_ANSIBLE_ROLES_REQUIREMENTS}}"
    cmds:
      - mkdir -p .config/go/roles
      - "{{.TASK_GO_ANSIBLE_GALAXY_CMD}} install -r {{.TASK_GO_ANSIBLE_ROLES_REQUIREMENTS}} --roles-path .config/go/roles"
      - cmd: echo "✅ Ansible roles installed successfully"
        silent: true

  install:
    desc: |
      ℹ️ Description:
        Installs Go using Ansible automation

      🔧 Variables:
        - TASK_GO_ANSIBLE_CMD: Ansible command path
        - TASK_GO_ANSIBLE_PLAYBOOK_FILE: Ansible playbook location
        - TASK_GO_VERSION: Major version of Go to install (default: 1.24.1)
        - TASK_GO_CHECKSUM: SHA256 checksum of the Go download (default: cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073)

      🔐 Preconditions:
        - Dependencies must be installed
        - Roles must be installed

      🔄 Execution:
        Runs Ansible playbook for Go installation
    status:
      - command -v go &> /dev/null
    preconditions:
      - sh: "test -f {{.TASK_GO_ANSIBLE_PLAYBOOK_FILE}}"
        msg: "❌ Playbook file not found at {{.TASK_GO_ANSIBLE_PLAYBOOK_FILE}}"
    cmds:
      - defer: { task: cleanup }
      - task: install:roles
      - |
        {{.TASK_GO_ANSIBLE_CMD}} \
          -i {{.TASK_GO_ANSIBLE_INVENTORY_TARGET}}, \
          -c local \
          -e "go_version={{.TASK_GO_VERSION}}" \
          -e "go_checksum={{.TASK_GO_CHECKSUM}}" \
          {{.TASK_GO_ANSIBLE_PLAYBOOK_FILE}}
      - cmd: echo "✅ Go installed successfully"
        silent: true

  cleanup:
    internal: true
    cmds:
      - rm -rf .config/go/roles
      - rm -rf {{.TASK_GO_VENV_DIR}}
      - cmd: echo "✅ Cleanup completed"
        silent: true
