---
version: "3"

vars:
  TASK_GO_ENABLED: '{{.TASK_GO_ENABLED | default "true"}}'
  TASK_GO_ANSIBLE_ROLES_REQUIREMENTS: '{{.TASK_GO_ANSIBLE_ROLES_REQUIREMENTS | default ".config/go/requirements.yml"}}'
  TASK_GO_ANSIBLE_PLAYBOOK_FILE: '{{.TASK_GO_ANSIBLE_PLAYBOOK_FILE | default ".config/go/playbook.yml"}}'
  TASK_GO_ANSIBLE_INVENTORY_TARGET: "localhost" # DevSkim: ignore DS162092
  TASK_GO_VERSION: '{{.TASK_GO_VERSION | default "1.24.1"}}'
  TASK_GO_CHECKSUM: '{{.TASK_GO_CHECKSUM | default "cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073"}}' # DevSkim: ignore DS173237

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  LANGUAGE: "C.UTF-8"
  ANSIBLE_ROLES_PATH: ".config/go/roles"

tasks:
  install:roles:
    desc: |
      ℹ️ Description:
        Installs required Ansible roles

      🔧 Variables:
        - TASK_GO_ANSIBLE_GALAXY_CMD: Ansible Galaxy command path
        - TASK_GO_ANSIBLE_ROLES_REQUIREMENTS: Roles requirements file path

      🔐 Preconditions:
        - Dependencies must be installed

      🔄 Execution:
        Installs required Ansible roles
    preconditions:
      - sh: "test -f {{.TASK_GO_ANSIBLE_ROLES_REQUIREMENTS}}"
        msg: "❌ Roles requirements file not found at {{.TASK_GO_ANSIBLE_ROLES_REQUIREMENTS}}"
    cmds:
      - cmd: echo "🔄 Starting install roles phase"
        silent: true
      - mkdir -p .config/go/roles
      - "{{.TASK_ANSIBLE_COMMAND}} ansible-galaxy install -r {{.TASK_GO_ANSIBLE_ROLES_REQUIREMENTS}} --roles-path .config/go/roles"
      - cmd: echo "🎉 Install roles phase completed successfully"
        silent: true

  install:
    desc: |
      ℹ️ Description:
        Installs Go using Ansible automation

      🔧 Variables:
        - TASK_GO_ANSIBLE_CMD: Ansible command path
        - TASK_GO_ANSIBLE_PLAYBOOK_FILE: Ansible playbook location
        - TASK_GO_VERSION: Major version of Go to install (default: 1.24.1)
        - TASK_GO_CHECKSUM: SHA256 checksum of the Go download (default: cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073)

      🔐 Preconditions:
        - Dependencies must be installed
        - Roles must be installed

      🔄 Execution:
        Runs Ansible playbook for Go installation
    status:
      - command -v go &> /dev/null
    preconditions:
      - sh: "test -f {{.TASK_GO_ANSIBLE_PLAYBOOK_FILE}}"
        msg: "❌ Playbook file not found at {{.TASK_GO_ANSIBLE_PLAYBOOK_FILE}}"
    cmds:
      - cmd: echo "🔄 Starting go installation phase"
        silent: true
      - defer: { task: cleanup }
      - task: install:roles
      - |
        {{.TASK_ANSIBLE_COMMAND}} ansible-playbook \
          -i {{.TASK_GO_ANSIBLE_INVENTORY_TARGET}}, \
          -c local \
          -e "go_version={{.TASK_GO_VERSION}}" \
          -e "go_checksum={{.TASK_GO_CHECKSUM}}" \
          {{.TASK_GO_ANSIBLE_PLAYBOOK_FILE}}
      - cmd: echo "🎉 Go installation phase completed successfully"
        silent: true

  cleanup:
    internal: true
    cmds:
      - cmd: echo "🔄 Starting cleanup phase"
        silent: true
      - rm -rf .config/go/roles
      - rm -rf {{.TASK_GO_VENV_DIR}}
      - cmd: echo "🎉 Cleanup phase completed successfully"
        silent: true
