# kics-scan ignore
---
services:
  ubuntu:
    build:
      context: ../..
      dockerfile: .config/devcontainer/ubuntu/Dockerfile
      args:
        USER: ${USER:-ubuntu}
        http_proxy: ${http_proxy:-}
        HTTP_PROXY: ${HTTP_PROXY:-}
        https_proxy: ${https_proxy:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}:/home/${USER:-ubuntu}
      - /sys/fs/cgroup:/sys/fs/cgroup
    environment:
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
    working_dir: ${PWD:-/home/ubuntu/workspace/project}
    init: true
    privileged: true
    network_mode: host
    group_add:
      - docker
    cap_add:
      - ALL
    cgroup: private
    healthcheck:
      test: ["CMD", "task", "--version"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    tty: true
    stdin_open: true
    command: ["tail", "-f", "/dev/null"]
