---
- name: Install Docker-CE
  hosts: localhost # DevSkim: ignore DS162092
  become: true
  gather_facts: true

  vars:
    current_user: "{{ lookup('env', 'USER') }}"

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.core_dependencies
    - role: robertdebock.docker_ce
      docker_ce_privileged_users:
        - "{{ current_user }}"
